// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final dashboardPageHandle = ffai.ProjectPageHandle<DashboardPageParams, DashboardPageState>(
  name: "DashboardPage",
  key: "Scaffold_rdu993fx",
  route: "dashboard",
  params: const DashboardPageParams(),
  state: const DashboardPageState(),
  widgets: DashboardPageWidgets.tree,
);

final class DashboardPageParams {
  const DashboardPageParams();
}

final class DashboardPageState {
  const DashboardPageState();
  ffai.ProjectStateFieldHandle get driveMatches =>
      const ffai.ProjectStateFieldHandle(
        name: "driveMatches",
        key: "oa3250rt",
        typeName: "List<DataStruct<FootMatch>>",
      );
  ffai.ProjectStateFieldHandle get duties =>
      const ffai.ProjectStateFieldHandle(
        name: "duties",
        key: "ls1t8qfi",
        typeName: "List<DataStruct<BarDuty>>",
      );
  ffai.ProjectStateFieldHandle get matches =>
      const ffai.ProjectStateFieldHandle(
        name: "matches",
        key: "8rzvw8e1",
        typeName: "List<DataStruct<FootMatch>>",
      );
}

abstract final class DashboardPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_rdu993fx",
      type: "Scaffold",
      path: "DashboardPage",
      name: "DashboardPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0xyrsmmo",
            type: "AppBar",
            path: "DashboardPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_g61pvwk5",
                  type: "Container",
                  path: "DashboardPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "oylp4ise",
                      type: "Image",
                      path: "DashboardPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_lpjbutnm",
                  type: "Text",
                  path: "DashboardPage.appBar[0].title[0]",
                  name: "DashboardAppBarTitle",
                  text: "Dashboard",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "o626fdmg",
            type: "Stack",
            path: "DashboardPage.body[0]",
            name: "DashboardPageBodyStack",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_4ip8iegb",
                type: "Column",
                path: "DashboardPage.body[0].children[0]",
                name: "Column",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_o474qvlo",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[0]",
                    name: "DashboardTeamSwitcher",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "ListView_odjpd1oz",
                        type: "ListView",
                        path: "DashboardPage.body[0].children[0].children[0].children[0]",
                        name: "DashboardTeamSwitcherList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_xahtyby5",
                            type: "Row",
                            path: "DashboardPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "DashboardTeamSwitcherItem",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_5ad3ejmq",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "DashboardTeamSwitcherActiveChip",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_1vlqmrw1",
                                    type: "Text",
                                    path: "DashboardPage.body[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                    name: "DashboardTeamSwitcherActiveName",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_t1aqzmeo",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "DashboardTeamSwitcherChip",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_b4d2383t",
                                    type: "Text",
                                    path: "DashboardPage.body[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                    name: "DashboardTeamSwitcherName",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_93klsbuv",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[1]",
                    name: "Container",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_pej4ul6o",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[2]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_79k7iv29",
                        type: "Text",
                        path: "DashboardPage.body[0].children[0].children[2].children[0]",
                        name: "Text",
                        text: "Mijn Wedstrijden",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_w7556a4v",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[3]",
                    name: "DashboardMatchesContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_t294fthy",
                        type: "Column",
                        path: "DashboardPage.body[0].children[0].children[3].children[0]",
                        name: "DashboardMatchesContainerCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ListView_pnzx12z6",
                            type: "ListView",
                            path: "DashboardPage.body[0].children[0].children[3].children[0].children[0]",
                            name: "DashboardMatchesList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_mnu9qijs",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0]",
                                name: "DashboardMatchCard",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_z3ueir3j",
                                    type: "Row",
                                    path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0]",
                                    name: "DashboardMatchRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "lfoxlgrs",
                                        type: "CircleImage",
                                        path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[0]",
                                        name: "DashboardMatchOpponentLogo",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kobyjonp",
                                        type: "Icon",
                                        path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_extv1jvc",
                                        type: "Column",
                                        path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2]",
                                        name: "DashboardMatchInfo",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_le80re68",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[0]",
                                            name: "DashboardMatchOpponent",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_nuxznew9",
                                            type: "Row",
                                            path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1]",
                                            name: "DashboardMatchMetaRow",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_k8vv18py",
                                                type: "Row",
                                                path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[0]",
                                                name: "DashboardMatchHomeAwayRow",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_bjnvqffo",
                                                    type: "Container",
                                                    path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[0].children[0]",
                                                    name: "DashboardMatchThuisBadge",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Text_ykfij80d",
                                                        type: "Text",
                                                        path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[0].children[0].children[0]",
                                                        name: "DashboardMatchThuisText",
                                                        text: "Thuis",
                                                      ),
                                                    ],
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Container_at6dj7jb",
                                                    type: "Container",
                                                    path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[0].children[1]",
                                                    name: "DashboardMatchUitBadge",
                                                    children: <ffai.ProjectWidgetHandle>[
                                                      ffai.ProjectWidgetHandle(
                                                        key: "Text_mbc949sc",
                                                        type: "Text",
                                                        path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[0].children[1].children[0]",
                                                        name: "DashboardMatchUitText",
                                                        text: "Uit",
                                                      ),
                                                    ],
                                                  ),
                                                ],
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_f7yqce9u",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[1].children[1]",
                                                name: "DashboardMatchDate",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_arg6t8hy",
                                            type: "Row",
                                            path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[2]",
                                            name: "DashboardMatchLocationRow",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_i7h55afb",
                                                type: "Icon",
                                                path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[2].children[0]",
                                                name: "Icon",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_03epp44g",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[3].children[0].children[0].children[0].children[0].children[2].children[2].children[1]",
                                                name: "DashboardMatchLocation",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_s355pdo6",
                            type: "Text",
                            path: "DashboardPage.body[0].children[0].children[3].children[0].children[1]",
                            name: "DashboardMatchesEmpty",
                            text: "Niets gepland",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_yfw1ewap",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[4]",
                    name: "Container",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_2aq559gk",
                        type: "Text",
                        path: "DashboardPage.body[0].children[0].children[4].children[0]",
                        name: "Text",
                        text: "Mijn bardiensten",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_vurxmw1h",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[5]",
                    name: "DashboardDutiesContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_huhaem9u",
                        type: "Column",
                        path: "DashboardPage.body[0].children[0].children[5].children[0]",
                        name: "DashboardDutiesContainerCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ListView_y34ufx10",
                            type: "ListView",
                            path: "DashboardPage.body[0].children[0].children[5].children[0].children[0]",
                            name: "DashboardDutiesList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_8qxgcrne",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0]",
                                name: "DashboardDutyCard",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_62qk9a5s",
                                    type: "Row",
                                    path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0].children[0]",
                                    name: "DashboardDutyRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_df4pdo5i",
                                        type: "Icon",
                                        path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_15dycu0h",
                                        type: "Column",
                                        path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0].children[0].children[1]",
                                        name: "DashboardDutyInfo",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ttr6vetj",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0].children[0].children[1].children[0]",
                                            name: "DashboardDutyShift",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_12ziadu6",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[5].children[0].children[0].children[0].children[0].children[1].children[1]",
                                            name: "DashboardDutyDate",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_f8i2iwa8",
                            type: "Text",
                            path: "DashboardPage.body[0].children[0].children[5].children[0].children[1]",
                            name: "DashboardDutiesEmpty",
                            text: "Niets gepland",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_tqxy5sh5",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[6]",
                    name: "DashboardDriveLabelContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_1mze090q",
                        type: "Text",
                        path: "DashboardPage.body[0].children[0].children[6].children[0]",
                        name: "DashboardDriveLabel",
                        text: "Mijn Rijschema",
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_vaea0dpp",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[7]",
                    name: "DashboardDriveContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_4wjwffjw",
                        type: "Column",
                        path: "DashboardPage.body[0].children[0].children[7].children[0]",
                        name: "DashboardDriveContainerCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "ListView_wz1c1vvm",
                            type: "ListView",
                            path: "DashboardPage.body[0].children[0].children[7].children[0].children[0]",
                            name: "DashboardDriveList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_fvbrtmcu",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0]",
                                name: "DashboardDriveCard",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_17itoaq4",
                                    type: "Row",
                                    path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0].children[0]",
                                    name: "DashboardDriveRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_056k9hkf",
                                        type: "Icon",
                                        path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_0g0dnc37",
                                        type: "Column",
                                        path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0].children[0].children[1]",
                                        name: "DashboardDriveInfo",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_wxtv0e7l",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0].children[0].children[1].children[0]",
                                            name: "DashboardDriveOpponent",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_5hkzrs9s",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[7].children[0].children[0].children[0].children[0].children[1].children[1]",
                                            name: "DashboardDriveDate",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_c82b7f6t",
                            type: "Text",
                            path: "DashboardPage.body[0].children[0].children[7].children[0].children[1]",
                            name: "DashboardDriveEmpty",
                            text: "Niets gepland",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_tqtj50gl",
                    type: "Container",
                    path: "DashboardPage.body[0].children[0].children[8]",
                    name: "DashboardTrainingsContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_qdi3e48r",
                        type: "Column",
                        path: "DashboardPage.body[0].children[0].children[8].children[0]",
                        name: "DashboardTrainingsCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_4fvk383c",
                            type: "Text",
                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[0]",
                            name: "DashboardTrainingsHeader",
                            text: "Mijn trainingen",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ListView_3mn45koq",
                            type: "ListView",
                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1]",
                            name: "DashboardTrainingsList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_anks3ylp",
                                type: "Container",
                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0]",
                                name: "DashboardTrainingCard",
                                triggers: const <String>[
                                  "ON_TAP",
                                ],
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_wcptzkjn",
                                    type: "Row",
                                    path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0]",
                                    name: "DashTrainRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_nvexm2z6",
                                        type: "Icon",
                                        path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Column_yl0c4s6h",
                                        type: "Column",
                                        path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1]",
                                        name: "DashTrainInfo",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_4u23szz9",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[0]",
                                            name: "DashTrainDay",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_h7elda4u",
                                            type: "Row",
                                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[1]",
                                            name: "DashTrainDT",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_t7xpdw04",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[1].children[0]",
                                                name: "DashTrainDate",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_m8htgljm",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[1].children[1]",
                                                name: "DashTrainTime",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_5fcqg6m4",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[2]",
                                            name: "DashTrainLoc",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_t7wa9qw6",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[3]",
                                            name: "DashTrainStatus",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Row_rn21b3kq",
                                            type: "Row",
                                            path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[4]",
                                            name: "DashTrainStatusRow",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_h8f69mbr",
                                                type: "Icon",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[4].children[0]",
                                                name: "Icon",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_4pil2wsy",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[4].children[1]",
                                                name: "DashTrainAangemeld",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_w8rsjbii",
                                                type: "Icon",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[4].children[2]",
                                                name: "Icon",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_qx3jon0w",
                                                type: "Text",
                                                path: "DashboardPage.body[0].children[0].children[8].children[0].children[1].children[0].children[0].children[1].children[4].children[3]",
                                                name: "DashTrainAfgemeld",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_1ip2mcvx",
                    type: "Column",
                    path: "DashboardPage.body[0].children[0].children[9]",
                    name: "GuestInvitationsContainer",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_xuwkoy64",
                        type: "Container",
                        path: "DashboardPage.body[0].children[0].children[9].children[0]",
                        name: "GuestInvHeaderWrap",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_rev96qot",
                            type: "Text",
                            path: "DashboardPage.body[0].children[0].children[9].children[0].children[0]",
                            name: "GuestInvHeader",
                            text: "Mijn uitnodigingen",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "ListView_dvpd7tgn",
                        type: "ListView",
                        path: "DashboardPage.body[0].children[0].children[9].children[1]",
                        name: "GuestInvitationsList",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_cxy35mti",
                            type: "Container",
                            path: "DashboardPage.body[0].children[0].children[9].children[1].children[0]",
                            name: "GuestInvCard",
                            triggers: const <String>[
                              "ON_TAP",
                            ],
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_5tjmr4zf",
                                type: "Column",
                                path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0]",
                                name: "GuestInvInfo",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_306qd8m7",
                                    type: "Text",
                                    path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[0]",
                                    name: "GuestInvTag",
                                    text: "Uitgenodigd als gastspeler",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_orp378k6",
                                    type: "Text",
                                    path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[1]",
                                    name: "GuestInvOpponent",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_clcmxyv6",
                                    type: "Row",
                                    path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[2]",
                                    name: "GuestInvMetaRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xhbpfw40",
                                        type: "Container",
                                        path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[2].children[0]",
                                        name: "GuestInvHomeAwayBadge",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_k7nxx5kj",
                                            type: "Text",
                                            path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[2].children[0].children[0]",
                                            name: "GuestInvHomeAway",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_0yah7das",
                                        type: "Text",
                                        path: "DashboardPage.body[0].children[0].children[9].children[1].children[0].children[0].children[2].children[1]",
                                        name: "GuestInvDate",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ltkjbvrn",
                type: "Container",
                path: "DashboardPage.body[0].children[1]",
                name: "ChatBadgeOverlay",
              ),
            ],
          ),
        ],
        "drawer": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Drawer_6e2zuz9b",
            type: "Drawer",
            path: "DashboardPage.drawer[0]",
            name: "AppDrawer",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_lf801f66",
                type: "Column",
                path: "DashboardPage.drawer[0].children[0]",
                name: "DrawerMenuColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_s726s5uu",
                    type: "Container",
                    path: "DashboardPage.drawer[0].children[0].children[0]",
                    name: "DrawerHeader",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_p0hzh5rc",
                        type: "Column",
                        path: "DashboardPage.drawer[0].children[0].children[0].children[0]",
                        name: "DrawerHeaderColumn",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_jlhkb2i3",
                            type: "Container",
                            path: "DashboardPage.drawer[0].children[0].children[0].children[0].children[0]",
                            name: "DrawerHeaderAvatar",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "cmhirnkt",
                                type: "CircleImage",
                                path: "DashboardPage.drawer[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "DrawerHeaderPhoto",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Icon_at9fcmtn",
                                type: "Icon",
                                path: "DashboardPage.drawer[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_v2th6pcc",
                            type: "Text",
                            path: "DashboardPage.drawer[0].children[0].children[0].children[0].children[1]",
                            name: "DrawerHeaderName",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ayccrx85",
                            type: "Text",
                            path: "DashboardPage.drawer[0].children[0].children[0].children[0].children[2]",
                            name: "DrawerHeaderEmail",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_7d35zz5i",
                    type: "ListTile",
                    path: "DashboardPage.drawer[0].children[0].children[1]",
                    name: "DrawerTileHome",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_zy0ngtj5",
                    type: "ListTile",
                    path: "DashboardPage.drawer[0].children[0].children[2]",
                    name: "DrawerTileNews",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_qqb6dl3i",
                    type: "ListTile",
                    path: "DashboardPage.drawer[0].children[0].children[3]",
                    name: "DrawerTileDocs",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_ye0f0zir",
                    type: "ListTile",
                    path: "DashboardPage.drawer[0].children[0].children[4]",
                    name: "DrawerTileProfiel",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_s62wtfcy",
                    type: "ListTile",
                    path: "DashboardPage.drawer[0].children[0].children[5]",
                    name: "DrawerTileBug",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_r2zcvze6",
                    type: "Container",
                    path: "DashboardPage.drawer[0].children[0].children[6]",
                    name: "DrawerFooterSpacer",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_3me7586o",
                    type: "Container",
                    path: "DashboardPage.drawer[0].children[0].children[7]",
                    name: "DrawerFooterLogoWrap",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_1b99fc8g",
                        type: "Row",
                        path: "DashboardPage.drawer[0].children[0].children[7].children[0]",
                        name: "DrawerFooterLogoRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "r5jz5krx",
                            type: "Image",
                            path: "DashboardPage.drawer[0].children[0].children[7].children[0].children[0]",
                            name: "DrawerFooterLogo",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
        "floatingActionButton": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "FloatingActionButton_1fdiymou",
            type: "FloatingActionButton",
            path: "DashboardPage.floatingActionButton[0]",
            name: "QuickActionsFab",
            triggers: const <String>[
              "ON_TAP",
            ],
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Icon_yxupk4mw",
                type: "Icon",
                path: "DashboardPage.floatingActionButton[0].children[0]",
                name: "FAB Icon",
              ),
            ],
          ),
        ],
      },
    ),
  );
}

