// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final opstellingPageHandle = ffai.ProjectPageHandle<OpstellingPageParams, OpstellingPageState>(
  name: "OpstellingPage",
  key: "Scaffold_g8pt01d6",
  route: "opstelling",
  params: const OpstellingPageParams(),
  state: const OpstellingPageState(),
  widgets: OpstellingPageWidgets.tree,
);

final class OpstellingPageParams {
  const OpstellingPageParams();
  ffai.ProjectParamHandle get matchId =>
      const ffai.ProjectParamHandle(
        name: "matchId",
        key: "ru8ywbhx",
        typeName: "String",
      );
  ffai.ProjectParamHandle get teamId =>
      const ffai.ProjectParamHandle(
        name: "teamId",
        key: "pqh4z1hs",
        typeName: "String",
      );
  ffai.ProjectParamHandle get teamName =>
      const ffai.ProjectParamHandle(
        name: "teamName",
        key: "by8z9pbg",
        typeName: "String",
      );
}

final class OpstellingPageState {
  const OpstellingPageState();
}

abstract final class OpstellingPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_g8pt01d6",
      type: "Scaffold",
      path: "OpstellingPage",
      name: "OpstellingPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_5bd3p5lc",
            type: "AppBar",
            path: "OpstellingPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_mualmp76",
                  type: "Container",
                  path: "OpstellingPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "l02n68dm",
                      type: "Image",
                      path: "OpstellingPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_n7g6eh3c",
                  type: "Text",
                  path: "OpstellingPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Opstelling",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_nxvzebbt",
            type: "Column",
            path: "OpstellingPage.body[0]",
            name: "OpstellingRootColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_zx6lujkz",
                type: "Text",
                path: "OpstellingPage.body[0].children[0]",
                name: "OpstellingTeamNaam",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_akuq2xb3",
                type: "Container",
                path: "OpstellingPage.body[0].children[1]",
                name: "OpstellingMeldingKaart Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_uzy2i29k",
                    type: "Container",
                    path: "OpstellingPage.body[0].children[1].children[0]",
                    name: "OpstellingMeldingKaart",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_wwvpuu2d",
                        type: "Text",
                        path: "OpstellingPage.body[0].children[1].children[0].children[0]",
                        name: "OpstellingMelding",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Row_emht2d8w",
                type: "Row",
                path: "OpstellingPage.body[0].children[2]",
                name: "OpstellingTabs",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_omqjvx8m",
                    type: "Column",
                    path: "OpstellingPage.body[0].children[2].children[0]",
                    name: "OpstellingTabveld",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_u5jnyxgf",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[0].children[0]",
                        name: "OpstellingTabveldAan",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_r5pzqtds",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "OpstellingTabveldAanRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_ggianlgz",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_tco4zapt",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[0].children[0].children[0].children[1]",
                                name: "OpstellingTabveldAanLabel",
                                text: "Opstelling",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_p9fcle1z",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[0].children[1]",
                        name: "OpstellingTabveldUit",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_fyg2v6ii",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[0].children[1].children[0]",
                            name: "OpstellingTabveldUitRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_9ncbfd1w",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[0].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_d6bp3eq4",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[0].children[1].children[0].children[1]",
                                name: "OpstellingTabveldUitLabel",
                                text: "Opstelling",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_ekr1a37p",
                    type: "Column",
                    path: "OpstellingPage.body[0].children[2].children[1]",
                    name: "OpstellingTabwissels",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_p7eio7ga",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[1].children[0]",
                        name: "OpstellingTabwisselsAan",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_jrqqmlra",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[1].children[0].children[0]",
                            name: "OpstellingTabwisselsAanRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_emqsbmwn",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[1].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_498w2fdv",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[1].children[0].children[0].children[1]",
                                name: "OpstellingTabwisselsAanLabel",
                                text: "Wissels",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_oi0h2zw6",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[1].children[1]",
                        name: "OpstellingTabwisselsUit",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_u42os4yb",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[1].children[1].children[0]",
                            name: "OpstellingTabwisselsUitRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_n3xrq2ni",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[1].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_o7876qnx",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[1].children[1].children[0].children[1]",
                                name: "OpstellingTabwisselsUitLabel",
                                text: "Wissels",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Column_k17mk6ck",
                    type: "Column",
                    path: "OpstellingPage.body[0].children[2].children[2]",
                    name: "OpstellingTabinstellingen",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_yzbdwese",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[2].children[0]",
                        name: "OpstellingTabinstellingenAan",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_o13ivq6l",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[2].children[0].children[0]",
                            name: "OpstellingTabinstellingenAanRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_2avf1g6z",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[2].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_pqlberp4",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[2].children[0].children[0].children[1]",
                                name: "OpstellingTabinstellingenAanLabel",
                                text: "Instellingen",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_1vuyxtzl",
                        type: "Container",
                        path: "OpstellingPage.body[0].children[2].children[2].children[1]",
                        name: "OpstellingTabinstellingenUit",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_namwo7lv",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[2].children[2].children[1].children[0]",
                            name: "OpstellingTabinstellingenUitRow",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_aavs6yyd",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[2].children[2].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_zd7vvzca",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[2].children[2].children[1].children[0].children[1]",
                                name: "OpstellingTabinstellingenUitLabel",
                                text: "Instellingen",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_fomqgsl6",
                type: "Container",
                path: "OpstellingPage.body[0].children[3]",
                name: "OpstellingBordWrap",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_3gacxpfm",
                    type: "Container",
                    path: "OpstellingPage.body[0].children[3].children[0]",
                    name: "OpstellingBord",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ombz6f6f",
                type: "Container",
                path: "OpstellingPage.body[0].children[4]",
                name: "OpstellingWisselWrap",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_3jr4yoei",
                    type: "Container",
                    path: "OpstellingPage.body[0].children[4].children[0]",
                    name: "OpstellingWissels",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_f2romd7k",
                type: "Text",
                path: "OpstellingPage.body[0].children[5]",
                name: "OpstellingAlleenLezen",
                text: "Je kunt deze opstelling bekijken, maar niet aanpassen.",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_8p7428bi",
                type: "Container",
                path: "OpstellingPage.body[0].children[6]",
                name: "OpstellingInstellingen Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_qcbg1u4c",
                    type: "Container",
                    path: "OpstellingPage.body[0].children[6].children[0]",
                    name: "OpstellingInstellingen",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_jtqt464l",
                        type: "Column",
                        path: "OpstellingPage.body[0].children[6].children[0].children[0]",
                        name: "OpstellingInstellingenCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_x5ckn41z",
                            type: "Row",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[0]",
                            name: "OpstellingInstellingenKop",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_esvc7nol",
                                type: "Icon",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_6z9p0npv",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[0].children[1]",
                                name: "OpstellingInstellingenTitel",
                                text: "Wedstrijdinstellingen",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_fiy9sbd8",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1]",
                            name: "OpstellingAantalCol",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_fny486op",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[0]",
                                name: "OpstellingAantalLabel",
                                text: "Aantal spelers op het veld",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_eb5imlnb",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1]",
                                name: "OpstellingAantalChips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_d2va7lm1",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0]",
                                    name: "OpstellingAantal0",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_eh2e2ywn",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0]",
                                        name: "OpstellingAantalAan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_0nzaml0g",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingAantalAanLabel0",
                                            text: "6",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_o5z10k2b",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[1]",
                                        name: "OpstellingAantalUit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_8gq9lddl",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingAantalUitLabel0",
                                            text: "6",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_3dsosvp9",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[1]",
                                    name: "OpstellingAantal1",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_z1geygg0",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[1].children[0]",
                                        name: "OpstellingAantalAan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_im6fce6o",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingAantalAanLabel1",
                                            text: "8",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_o3px01mk",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[1].children[1]",
                                        name: "OpstellingAantalUit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_wytiv3js",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingAantalUitLabel1",
                                            text: "8",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_d146idb3",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[2]",
                                    name: "OpstellingAantal2",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_a6pgpnn8",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[2].children[0]",
                                        name: "OpstellingAantalAan2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_fjeddit6",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[2].children[0].children[0]",
                                            name: "OpstellingAantalAanLabel2",
                                            text: "9",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_wfra1735",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[2].children[1]",
                                        name: "OpstellingAantalUit2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_tfssei4w",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[2].children[1].children[0]",
                                            name: "OpstellingAantalUitLabel2",
                                            text: "9",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_pgpxog4u",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[3]",
                                    name: "OpstellingAantal3",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_6klj9l19",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[3].children[0]",
                                        name: "OpstellingAantalAan3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_glevqfr4",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[3].children[0].children[0]",
                                            name: "OpstellingAantalAanLabel3",
                                            text: "11",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_fvwvsou3",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[3].children[1]",
                                        name: "OpstellingAantalUit3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ql4e61jx",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[1].children[1].children[3].children[1].children[0]",
                                            name: "OpstellingAantalUitLabel3",
                                            text: "11",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_o22oj14w",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2]",
                            name: "OpstellingFormatie6Col",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_ilpvap9e",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[0]",
                                name: "OpstellingFormatie6Label",
                                text: "Opstelling",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_sss23kf9",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1]",
                                name: "OpstellingFormatie6Chips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_c4nd3lyy",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[0]",
                                    name: "OpstellingFormatie60",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_cu3gvgsq",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[0].children[0]",
                                        name: "OpstellingFormatie6Aan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_k0nidfhn",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingFormatie6AanLabel0",
                                            text: "3-0-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_vppy1zh0",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[0].children[1]",
                                        name: "OpstellingFormatie6Uit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_axyp6khe",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingFormatie6UitLabel0",
                                            text: "3-0-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_zpq733vw",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[1]",
                                    name: "OpstellingFormatie61",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_9l52pqg7",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[1].children[0]",
                                        name: "OpstellingFormatie6Aan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_8pfnfaea",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingFormatie6AanLabel1",
                                            text: "2-1-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_b6qxq3i0",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[1].children[1]",
                                        name: "OpstellingFormatie6Uit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_blxde9yi",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingFormatie6UitLabel1",
                                            text: "2-1-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_sa9p4sbh",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[2]",
                                    name: "OpstellingFormatie62",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_aqyv8b7y",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[2].children[0]",
                                        name: "OpstellingFormatie6Aan2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_j9445d2z",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[2].children[0].children[0]",
                                            name: "OpstellingFormatie6AanLabel2",
                                            text: "2-2-1",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_yknur4sx",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[2].children[1]",
                                        name: "OpstellingFormatie6Uit2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_qe64d31m",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[2].children[1].children[2].children[1].children[0]",
                                            name: "OpstellingFormatie6UitLabel2",
                                            text: "2-2-1",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_hkj209j5",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3]",
                            name: "OpstellingFormatie8Col",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_bmi3bk99",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[0]",
                                name: "OpstellingFormatie8Label",
                                text: "Opstelling",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_65ypz7xd",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1]",
                                name: "OpstellingFormatie8Chips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_fbjsjhpb",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[0]",
                                    name: "OpstellingFormatie80",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_q6ivp5kq",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[0].children[0]",
                                        name: "OpstellingFormatie8Aan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ohiyroy1",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingFormatie8AanLabel0",
                                            text: "3-3-1",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_6x3eqv7y",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[0].children[1]",
                                        name: "OpstellingFormatie8Uit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_jlum81rq",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingFormatie8UitLabel0",
                                            text: "3-3-1",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_0o0s7u0y",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[1]",
                                    name: "OpstellingFormatie81",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_hcjixamk",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[1].children[0]",
                                        name: "OpstellingFormatie8Aan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_qs7yvjdv",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingFormatie8AanLabel1",
                                            text: "2-3-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_f29fn1ik",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[1].children[1]",
                                        name: "OpstellingFormatie8Uit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_qjq9z61f",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingFormatie8UitLabel1",
                                            text: "2-3-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_boucq62h",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[2]",
                                    name: "OpstellingFormatie82",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_dpmo85wv",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[2].children[0]",
                                        name: "OpstellingFormatie8Aan2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_lv8sxfvt",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[2].children[0].children[0]",
                                            name: "OpstellingFormatie8AanLabel2",
                                            text: "3-2-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_7dlxbf3p",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[2].children[1]",
                                        name: "OpstellingFormatie8Uit2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_bwn0ob2v",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[3].children[1].children[2].children[1].children[0]",
                                            name: "OpstellingFormatie8UitLabel2",
                                            text: "3-2-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_vbnwrth6",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4]",
                            name: "OpstellingFormatie9Col",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_vaerpomv",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[0]",
                                name: "OpstellingFormatie9Label",
                                text: "Opstelling",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_miu0boen",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1]",
                                name: "OpstellingFormatie9Chips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_83zfajth",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[0]",
                                    name: "OpstellingFormatie90",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_bg7m7d0s",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[0].children[0]",
                                        name: "OpstellingFormatie9Aan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_it4yhejc",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingFormatie9AanLabel0",
                                            text: "3-2-3",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_e23c113r",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[0].children[1]",
                                        name: "OpstellingFormatie9Uit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_xznubsz3",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingFormatie9UitLabel0",
                                            text: "3-2-3",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_6lj2wrlz",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[1]",
                                    name: "OpstellingFormatie91",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_upj47aya",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[1].children[0]",
                                        name: "OpstellingFormatie9Aan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_6vrsajp4",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingFormatie9AanLabel1",
                                            text: "3-3-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_fjesnwaw",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[1].children[1]",
                                        name: "OpstellingFormatie9Uit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_p8rjfrvm",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingFormatie9UitLabel1",
                                            text: "3-3-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_tz2194vz",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[2]",
                                    name: "OpstellingFormatie92",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_t4pfiqly",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[2].children[0]",
                                        name: "OpstellingFormatie9Aan2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_v8go8myd",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[2].children[0].children[0]",
                                            name: "OpstellingFormatie9AanLabel2",
                                            text: "4-3-1",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xai963wb",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[2].children[1]",
                                        name: "OpstellingFormatie9Uit2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_9ug0i25t",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[2].children[1].children[0]",
                                            name: "OpstellingFormatie9UitLabel2",
                                            text: "4-3-1",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_8b60dpv9",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[3]",
                                    name: "OpstellingFormatie93",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_g4uhsnh5",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[3].children[0]",
                                        name: "OpstellingFormatie9Aan3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_s82njl2z",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[3].children[0].children[0]",
                                            name: "OpstellingFormatie9AanLabel3",
                                            text: "2-3-3",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xs2kelrt",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[3].children[1]",
                                        name: "OpstellingFormatie9Uit3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_xp2j11ay",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[4].children[1].children[3].children[1].children[0]",
                                            name: "OpstellingFormatie9UitLabel3",
                                            text: "2-3-3",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_3p8s172e",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5]",
                            name: "OpstellingFormatie11Col",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_5zcmzrgl",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[0]",
                                name: "OpstellingFormatie11Label",
                                text: "Opstelling",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_kx0gj4vh",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1]",
                                name: "OpstellingFormatie11Chips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_joe248a4",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[0]",
                                    name: "OpstellingFormatie110",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_9hf1oyzt",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[0].children[0]",
                                        name: "OpstellingFormatie11Aan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ark9gxay",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel0",
                                            text: "4-3-3",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_09ovwhtc",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[0].children[1]",
                                        name: "OpstellingFormatie11Uit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_q1zigzeo",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel0",
                                            text: "4-3-3",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_3yg4ma9n",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[1]",
                                    name: "OpstellingFormatie111",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_eacwdf77",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[1].children[0]",
                                        name: "OpstellingFormatie11Aan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_mqszlr0y",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel1",
                                            text: "4-4-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ql41rpzi",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[1].children[1]",
                                        name: "OpstellingFormatie11Uit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_x36xux7x",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel1",
                                            text: "4-4-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_jko6oog6",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[2]",
                                    name: "OpstellingFormatie112",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xg2ysotx",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[2].children[0]",
                                        name: "OpstellingFormatie11Aan2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_f190akhn",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[2].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel2",
                                            text: "4-2-3-1",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_dr1ad3qb",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[2].children[1]",
                                        name: "OpstellingFormatie11Uit2",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_wrl7hsjw",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[2].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel2",
                                            text: "4-2-3-1",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_yr6i8py1",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[3]",
                                    name: "OpstellingFormatie113",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_uboqxm92",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[3].children[0]",
                                        name: "OpstellingFormatie11Aan3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_2occsghc",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[3].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel3",
                                            text: "4-1-3-2",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_ijrof0ce",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[3].children[1]",
                                        name: "OpstellingFormatie11Uit3",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_q5ywcit6",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[3].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel3",
                                            text: "4-1-3-2",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_b6pjva25",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[4]",
                                    name: "OpstellingFormatie114",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_j5s378qm",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[4].children[0]",
                                        name: "OpstellingFormatie11Aan4",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_z23s4v7c",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[4].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel4",
                                            text: "4-5-1",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_hwz4ru9g",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[4].children[1]",
                                        name: "OpstellingFormatie11Uit4",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_b9yoovsw",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[4].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel4",
                                            text: "4-5-1",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_zj6xd0w7",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[5]",
                                    name: "OpstellingFormatie115",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_yp1p0e64",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[5].children[0]",
                                        name: "OpstellingFormatie11Aan5",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_nsrlfpsw",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[5].children[0].children[0]",
                                            name: "OpstellingFormatie11AanLabel5",
                                            text: "3-4-3",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_g5b8q98m",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[5].children[1]",
                                        name: "OpstellingFormatie11Uit5",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_dh272cyf",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[5].children[1].children[5].children[1].children[0]",
                                            name: "OpstellingFormatie11UitLabel5",
                                            text: "3-4-3",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_ts6okwlp",
                            type: "Text",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[6]",
                            name: "OpstellingFormatieUitleg",
                            text: "De cijfers zijn de veldspelers; de keeper komt daar nog bij.",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_q937wo64",
                            type: "Column",
                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7]",
                            name: "OpstellingPeriodenCol",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_cv17omca",
                                type: "Text",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[0]",
                                name: "OpstellingPeriodenLabel",
                                text: "Wedstrijdformaat",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_twzl5m5u",
                                type: "Row",
                                path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1]",
                                name: "OpstellingPeriodenChips",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_mt9kbelc",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[0]",
                                    name: "OpstellingPerioden0",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_j7rvuulz",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[0].children[0]",
                                        name: "OpstellingPeriodenAan0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_yyotnqzp",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[0].children[0].children[0]",
                                            name: "OpstellingPeriodenAanLabel0",
                                            text: "2 helften",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_dan5zlve",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[0].children[1]",
                                        name: "OpstellingPeriodenUit0",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_4a53hxcu",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[0].children[1].children[0]",
                                            name: "OpstellingPeriodenUitLabel0",
                                            text: "2 helften",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_dla0ygln",
                                    type: "Row",
                                    path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[1]",
                                    name: "OpstellingPerioden1",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_zxvsvs5f",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[1].children[0]",
                                        name: "OpstellingPeriodenAan1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_gdmg0086",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[1].children[0].children[0]",
                                            name: "OpstellingPeriodenAanLabel1",
                                            text: "4 kwarten",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_l46pgkl4",
                                        type: "Container",
                                        path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[1].children[1]",
                                        name: "OpstellingPeriodenUit1",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_wubloo5n",
                                            type: "Text",
                                            path: "OpstellingPage.body[0].children[6].children[0].children[0].children[7].children[1].children[1].children[1].children[0]",
                                            name: "OpstellingPeriodenUitLabel1",
                                            text: "4 kwarten",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Column_y1stuwu8",
                type: "Column",
                path: "OpstellingPage.body[0].children[7]",
                name: "OpstellingKnoppen",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Text_2tpvpn62",
                    type: "Text",
                    path: "OpstellingPage.body[0].children[7].children[0]",
                    name: "OpstellingNotitieLabel",
                    text: "Notitie bij de opstelling",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "TextField_age7rvdw",
                    type: "TextField",
                    path: "OpstellingPage.body[0].children[7].children[1]",
                    name: "OpstellingNotitieVeld",
                    text: "Bijv. verzamelen om 8:15, of afspraken over de vaste opbouw.",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Text_w5bg7qx7",
                    type: "Text",
                    path: "OpstellingPage.body[0].children[7].children[2]",
                    name: "OpstellingNotitieUitleg",
                    text: "Alleen zichtbaar voor de coach en de leiders van dit elftal.",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_vwuhbszd",
                    type: "Button",
                    path: "OpstellingPage.body[0].children[7].children[3]",
                    name: "OpstellingOpslaan",
                    text: "Opslaan",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_nmg9nx58",
                    type: "Button",
                    path: "OpstellingPage.body[0].children[7].children[4]",
                    name: "OpstellingStandaardLaden",
                    text: "Standaard opstelling laden",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_7jhbcpgp",
                    type: "Button",
                    path: "OpstellingPage.body[0].children[7].children[5]",
                    name: "OpstellingNaarStandaard",
                    text: "Standaard opstelling",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_t502yhay",
                    type: "Button",
                    path: "OpstellingPage.body[0].children[7].children[6]",
                    name: "OpstellingVrijgeven",
                    text: "Vrijgeven voor spelers",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Button_btqythmt",
                    type: "Button",
                    path: "OpstellingPage.body[0].children[7].children[7]",
                    name: "OpstellingVerbergen",
                    text: "Verbergen voor spelers",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

