// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final rijschemaDetailPageHandle = ffai.ProjectPageHandle<RijschemaDetailPageParams, RijschemaDetailPageState>(
  name: "RijschemaDetailPage",
  key: "Scaffold_cz6k775k",
  route: "rijschema-detail",
  params: const RijschemaDetailPageParams(),
  state: const RijschemaDetailPageState(),
  widgets: RijschemaDetailPageWidgets.tree,
);

final class RijschemaDetailPageParams {
  const RijschemaDetailPageParams();
  ffai.ProjectParamHandle get matchId =>
      const ffai.ProjectParamHandle(
        name: "matchId",
        key: "47zrozad",
        typeName: "String",
      );
}

final class RijschemaDetailPageState {
  const RijschemaDetailPageState();
  ffai.ProjectStateFieldHandle get isLoading =>
      const ffai.ProjectStateFieldHandle(
        name: "isLoading",
        key: "rsyr7vu2",
        typeName: "Boolean",
      );
  ffai.ProjectStateFieldHandle get match =>
      const ffai.ProjectStateFieldHandle(
        name: "match",
        key: "2qmft67p",
        typeName: "DataStruct<FootMatch>",
      );
  ffai.ProjectStateFieldHandle get rijArrivalTime =>
      const ffai.ProjectStateFieldHandle(
        name: "rijArrivalTime",
        key: "5rli4e91",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijCoachName =>
      const ffai.ProjectStateFieldHandle(
        name: "rijCoachName",
        key: "x5pu5a5a",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijDatetime =>
      const ffai.ProjectStateFieldHandle(
        name: "rijDatetime",
        key: "sgw04all",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijDriverNames =>
      const ffai.ProjectStateFieldHandle(
        name: "rijDriverNames",
        key: "d9xthc8t",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijIsDriver =>
      const ffai.ProjectStateFieldHandle(
        name: "rijIsDriver",
        key: "pm3qbcls",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijIsHome =>
      const ffai.ProjectStateFieldHandle(
        name: "rijIsHome",
        key: "gqh6lqbh",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijLocation =>
      const ffai.ProjectStateFieldHandle(
        name: "rijLocation",
        key: "y5epc2ax",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijNotes =>
      const ffai.ProjectStateFieldHandle(
        name: "rijNotes",
        key: "nl5vwfxg",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijOpponent =>
      const ffai.ProjectStateFieldHandle(
        name: "rijOpponent",
        key: "si8xjgsq",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get rijTeamName =>
      const ffai.ProjectStateFieldHandle(
        name: "rijTeamName",
        key: "g5cpyx2x",
        typeName: "String",
      );
}

abstract final class RijschemaDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_cz6k775k",
      type: "Scaffold",
      path: "RijschemaDetailPage",
      name: "RijschemaDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_m450t2ed",
            type: "AppBar",
            path: "RijschemaDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "IconButton_8ejw97fw",
                  type: "IconButton",
                  path: "RijschemaDetailPage.appBar[0].actions[0]",
                  name: "RijschemaCalendarButton",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_gjq4drd9",
                  type: "Container",
                  path: "RijschemaDetailPage.appBar[0].actions[1]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "90pn4hod",
                      type: "Image",
                      path: "RijschemaDetailPage.appBar[0].actions[1].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_uc54injs",
                  type: "Text",
                  path: "RijschemaDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Rit details",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_5aa6n8k7",
            type: "Column",
            path: "RijschemaDetailPage.body[0]",
            name: "RijInfoColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Text_q3vvnlxh",
                type: "Text",
                path: "RijschemaDetailPage.body[0].children[0]",
                name: "RijTitle",
                text: "Wedstrijd details",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_wxlzkme2",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[1]",
                name: "RijInfoRow_rijTeamName",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_ndvybm6e",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_4k83716u",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[1].children[0].children[0]",
                        name: "Text",
                        text: "Eigen team",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_iac4ynjx",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[1].children[0].children[1]",
                        name: "RijInfoValue_rijTeamName",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_l2q0tfv8",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[2]",
                name: "RijInfoRow_rijOpponent",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_gp91txb2",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[2].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_7vbjxkc8",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[2].children[0].children[0]",
                        name: "Text",
                        text: "Tegenstander",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_qhms6q2g",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[2].children[0].children[1]",
                        name: "RijInfoValue_rijOpponent",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_nf565ove",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[3]",
                name: "RijInfoRow_rijDatetime",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_lc0dlu11",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[3].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_t1ip6tl6",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[3].children[0].children[0]",
                        name: "Text",
                        text: "Datum & Tijd",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_81th1orr",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[3].children[0].children[1]",
                        name: "RijInfoValue_rijDatetime",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ju7foxe8",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[4]",
                name: "RijInfoRow_rijLocation",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_4nu94d90",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[4].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_jncattcu",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[4].children[0].children[0]",
                        name: "Text",
                        text: "Locatie",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_71150p6v",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[4].children[0].children[1]",
                        name: "RijInfoValue_rijLocation",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_owtp67c4",
                type: "Button",
                path: "RijschemaDetailPage.body[0].children[5]",
                name: "RijNavigateButton",
                text: "Navigeer naar locatie",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_zsgdtswv",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[6]",
                name: "RijInfoRow_rijIsHome",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_x62t4tfw",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[6].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_3z23p19g",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[6].children[0].children[0]",
                        name: "Text",
                        text: "Thuis/Uit",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_goz3hpji",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[6].children[0].children[1]",
                        name: "RijInfoValue_rijIsHome",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_ftukx322",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[7]",
                name: "RijInfoRow_rijArrivalTime",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_9jh460cx",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[7].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_fwwrzl8n",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[7].children[0].children[0]",
                        name: "Text",
                        text: "Verzamelen",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_76k8tjc0",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[7].children[0].children[1]",
                        name: "RijInfoValue_rijArrivalTime",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_uuxoxgoa",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[8]",
                name: "RijInfoRow_rijCoachName",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_anvimd8a",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[8].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_17uu8dhx",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[8].children[0].children[0]",
                        name: "Text",
                        text: "Coach",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_jxjtc6el",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[8].children[0].children[1]",
                        name: "RijInfoValue_rijCoachName",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_6sicftnr",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[9]",
                name: "RijInfoRow_rijDriverNames",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_75ghh3wj",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[9].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_8mfaf4qk",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[9].children[0].children[0]",
                        name: "Text",
                        text: "Rijders",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_zdpax97u",
                        type: "Container",
                        path: "RijschemaDetailPage.body[0].children[9].children[0].children[1]",
                        name: "NameList_rijDriverNames",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_4zmb26u6",
                type: "Container",
                path: "RijschemaDetailPage.body[0].children[10]",
                name: "RijInfoRow_rijNotes",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_l8g7v939",
                    type: "Column",
                    path: "RijschemaDetailPage.body[0].children[10].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_bymhlb34",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[10].children[0].children[0]",
                        name: "Text",
                        text: "Notities",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_h2b3ycxl",
                        type: "Text",
                        path: "RijschemaDetailPage.body[0].children[10].children[0].children[1]",
                        name: "RijInfoValue_rijNotes",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_dquo5w4n",
                type: "Button",
                path: "RijschemaDetailPage.body[0].children[11]",
                name: "RijWisselButton",
                text: "Wissel aanvragen",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

