// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final standPageHandle = ffai.ProjectPageHandle<StandPageParams, StandPageState>(
  name: "StandPage",
  key: "Scaffold_nvxefp0k",
  route: "stand",
  params: const StandPageParams(),
  state: const StandPageState(),
  widgets: StandPageWidgets.tree,
);

final class StandPageParams {
  const StandPageParams();
}

final class StandPageState {
  const StandPageState();
}

abstract final class StandPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_nvxefp0k",
      type: "Scaffold",
      path: "StandPage",
      name: "StandPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0gpwwzjb",
            type: "AppBar",
            path: "StandPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_hi8qb9a0",
                  type: "Container",
                  path: "StandPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "xo0ko4wh",
                      type: "Image",
                      path: "StandPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_i6aetzch",
                  type: "Text",
                  path: "StandPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Stand",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_btaj8a4k",
            type: "Column",
            path: "StandPage.body[0]",
            name: "StandRootColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_h6cbl3yy",
                type: "Container",
                path: "StandPage.body[0].children[0]",
                name: "StandGeenData",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_5t2st63x",
                    type: "Column",
                    path: "StandPage.body[0].children[0].children[0]",
                    name: "StandGeenDataCol",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_5eqnz3av",
                        type: "Text",
                        path: "StandPage.body[0].children[0].children[0].children[0]",
                        name: "StandGeenDataTitel",
                        text: "Geen stand geladen voor dit elftal.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_9j3k5wv7",
                        type: "Text",
                        path: "StandPage.body[0].children[0].children[0].children[1]",
                        name: "StandGeenDataTeam",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_q3cvvlct",
                type: "Text",
                path: "StandPage.body[0].children[1]",
                name: "StandMelding",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_1h1j2vub",
                type: "Container",
                path: "StandPage.body[0].children[2]",
                name: "StandKaart Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_21d8eouh",
                    type: "Container",
                    path: "StandPage.body[0].children[2].children[0]",
                    name: "StandKaart",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_ulo1l6jz",
                        type: "Column",
                        path: "StandPage.body[0].children[2].children[0].children[0]",
                        name: "StandKaartCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_jvtpaipo",
                            type: "Container",
                            path: "StandPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "StandKopRij",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_ecwjfc6l",
                                type: "Row",
                                path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "StandKopRow",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ka4ht6o8",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                    name: "StandKop#",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_wgu9oxpv",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "StandKop#Tekst",
                                        text: "#",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ea0fhf3d",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                    name: "StandKopLogo",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_z5fb097k",
                                    type: "Text",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[2]",
                                    name: "StandKopTeam",
                                    text: "Team",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_oqjycebd",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[3]",
                                    name: "StandKopG",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_b6l7e6rh",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[3].children[0]",
                                        name: "StandKopGTekst",
                                        text: "G",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_h48y4wex",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[4]",
                                    name: "StandKopDS",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_g4jbymv0",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[4].children[0]",
                                        name: "StandKopDSTekst",
                                        text: "DS",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_e0bxbmri",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[5]",
                                    name: "StandKopP",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_i718rz25",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[5].children[0]",
                                        name: "StandKopPTekst",
                                        text: "P",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ListView_itk164kd",
                            type: "ListView",
                            path: "StandPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "StandList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_1btwy6d2",
                                type: "Container",
                                path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "StandRij",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_mmtj45w7",
                                    type: "Row",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                    name: "StandRijRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_a54j3bh8",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "StandPositieWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_c8dwfatx",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                            name: "StandPositie",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "2lw6ntks",
                                        type: "CircleImage",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[1]",
                                        name: "StandLogo",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_aox6wv4o",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[2]",
                                        name: "StandTeamEigen",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_iup4dnq5",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[3]",
                                        name: "StandTeamAnder",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_2qpwvy7j",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[4]",
                                        name: "StandGespeeldWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_j6dj57yf",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[4].children[0]",
                                            name: "StandGespeeld",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_6f8ro7sf",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[5]",
                                        name: "StandSaldoWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ugbok9n3",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[5].children[0]",
                                            name: "StandSaldo",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_xe7qma9o",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[6]",
                                        name: "StandPuntenWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_1xi0oumw",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[6].children[0]",
                                            name: "StandPunten",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

