// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final standPageHandle = ffai.ProjectPageHandle<StandPageParams, StandPageState>(
  name: "StandPage",
  key: "Scaffold_nvxefp0k",
  route: "stand",
  params: const StandPageParams(),
  state: const StandPageState(),
  widgets: StandPageWidgets.tree,
);

final class StandPageParams {
  const StandPageParams();
}

final class StandPageState {
  const StandPageState();
}

abstract final class StandPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_nvxefp0k",
      type: "Scaffold",
      path: "StandPage",
      name: "StandPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_0gpwwzjb",
            type: "AppBar",
            path: "StandPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_hi8qb9a0",
                  type: "Container",
                  path: "StandPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "xo0ko4wh",
                      type: "Image",
                      path: "StandPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_i6aetzch",
                  type: "Text",
                  path: "StandPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Stand",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_btaj8a4k",
            type: "Column",
            path: "StandPage.body[0]",
            name: "StandRootColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_erlq3jzj",
                type: "Container",
                path: "StandPage.body[0].children[0]",
                name: "StandGeenData",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_vsvunw9y",
                    type: "Column",
                    path: "StandPage.body[0].children[0].children[0]",
                    name: "StandGeenDataCol",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Text_52mrpxjr",
                        type: "Text",
                        path: "StandPage.body[0].children[0].children[0].children[0]",
                        name: "StandGeenDataTitel",
                        text: "Geen stand geladen voor dit elftal.",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Text_2pq219ch",
                        type: "Text",
                        path: "StandPage.body[0].children[0].children[0].children[1]",
                        name: "StandGeenDataTeam",
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_cdmuo1pj",
                type: "Text",
                path: "StandPage.body[0].children[1]",
                name: "StandMelding",
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_i0kf4mvx",
                type: "Container",
                path: "StandPage.body[0].children[2]",
                name: "StandKaart Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_wwy691au",
                    type: "Container",
                    path: "StandPage.body[0].children[2].children[0]",
                    name: "StandKaart",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_2fp2ejpt",
                        type: "Column",
                        path: "StandPage.body[0].children[2].children[0].children[0]",
                        name: "StandKaartCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_nmgcorzp",
                            type: "Container",
                            path: "StandPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "StandKopRij",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_h17afoer",
                                type: "Row",
                                path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "StandKopRow",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_cj53kyhd",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                    name: "StandKop#",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_9akbzcen",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "StandKop#Tekst",
                                        text: "#",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_nze4amkf",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[1]",
                                    name: "StandKopLogo",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_d24l5c5h",
                                    type: "Text",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[2]",
                                    name: "StandKopTeam",
                                    text: "Team",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_8xi69y8u",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[3]",
                                    name: "StandKopG",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_3kdgodps",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[3].children[0]",
                                        name: "StandKopGTekst",
                                        text: "G",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_sqgnr4qu",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[4]",
                                    name: "StandKopDS",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_mbryxbx5",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[4].children[0]",
                                        name: "StandKopDSTekst",
                                        text: "DS",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xpxamgqa",
                                    type: "Container",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[5]",
                                    name: "StandKopP",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_rku2otcu",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[0].children[0].children[5].children[0]",
                                        name: "StandKopPTekst",
                                        text: "P",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "ListView_b13rugd7",
                            type: "ListView",
                            path: "StandPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "StandList",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_uh4rnhwr",
                                type: "Container",
                                path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "StandRij",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_07c0qyty",
                                    type: "Row",
                                    path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                    name: "StandRijRow",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_3i4773ev",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "StandPositieWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_do7fx5py",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                            name: "StandPositie",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "i35wqbrc",
                                        type: "CircleImage",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[1]",
                                        name: "StandLogo",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ttjoyups",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[2]",
                                        name: "StandTeamEigen",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_uvxvonwc",
                                        type: "Text",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[3]",
                                        name: "StandTeamAnder",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_qyrf4tvb",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[4]",
                                        name: "StandGespeeldWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_ug5jluo7",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[4].children[0]",
                                            name: "StandGespeeld",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_wka6bc0y",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[5]",
                                        name: "StandSaldoWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_snbtyaj4",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[5].children[0]",
                                            name: "StandSaldo",
                                          ),
                                        ],
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Container_zsqkgnh7",
                                        type: "Container",
                                        path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[6]",
                                        name: "StandPuntenWrap",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_i99ayaav",
                                            type: "Text",
                                            path: "StandPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0].children[6].children[0]",
                                            name: "StandPunten",
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

