// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final trainingDetailPageHandle = ffai.ProjectPageHandle<TrainingDetailPageParams, TrainingDetailPageState>(
  name: "TrainingDetailPage",
  key: "Scaffold_ugu84our",
  route: "training-detail",
  params: const TrainingDetailPageParams(),
  state: const TrainingDetailPageState(),
  widgets: TrainingDetailPageWidgets.tree,
);

final class TrainingDetailPageParams {
  const TrainingDetailPageParams();
  ffai.ProjectParamHandle get afgelastReden =>
      const ffai.ProjectParamHandle(
        name: "afgelastReden",
        key: "w2ohogkb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get afmeldingen =>
      const ffai.ProjectParamHandle(
        name: "afmeldingen",
        key: "dvk0551g",
        typeName: "List<DataStruct<Afmelding>>",
      );
  ffai.ProjectParamHandle get date =>
      const ffai.ProjectParamHandle(
        name: "date",
        key: "fedg1u52",
        typeName: "String",
      );
  ffai.ProjectParamHandle get dayLabel =>
      const ffai.ProjectParamHandle(
        name: "dayLabel",
        key: "8wv8jfc7",
        typeName: "String",
      );
  ffai.ProjectParamHandle get isAfgelast =>
      const ffai.ProjectParamHandle(
        name: "isAfgelast",
        key: "nn9x8nkp",
        typeName: "String",
      );
  ffai.ProjectParamHandle get kleedkamer =>
      const ffai.ProjectParamHandle(
        name: "kleedkamer",
        key: "8i599a9x",
        typeName: "String",
      );
  ffai.ProjectParamHandle get location =>
      const ffai.ProjectParamHandle(
        name: "location",
        key: "j4fqpnqb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get magAfgelasten =>
      const ffai.ProjectParamHandle(
        name: "magAfgelasten",
        key: "us61te7s",
        typeName: "String",
      );
  ffai.ProjectParamHandle get mijnStatus =>
      const ffai.ProjectParamHandle(
        name: "mijnStatus",
        key: "f0c6wea0",
        typeName: "String",
      );
  ffai.ProjectParamHandle get scheduleId =>
      const ffai.ProjectParamHandle(
        name: "scheduleId",
        key: "tulrxfdo",
        typeName: "String",
      );
  ffai.ProjectParamHandle get startTime =>
      const ffai.ProjectParamHandle(
        name: "startTime",
        key: "ue0z4203",
        typeName: "String",
      );
}

final class TrainingDetailPageState {
  const TrainingDetailPageState();
  ffai.ProjectStateFieldHandle get localAfgelast =>
      const ffai.ProjectStateFieldHandle(
        name: "localAfgelast",
        key: "eyiwip3m",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get localAfgelastReden =>
      const ffai.ProjectStateFieldHandle(
        name: "localAfgelastReden",
        key: "sn0wqtca",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get localStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "localStatus",
        key: "mkxqui0d",
        typeName: "String",
      );
}

abstract final class TrainingDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ugu84our",
      type: "Scaffold",
      path: "TrainingDetailPage",
      name: "TrainingDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_esilfi4x",
            type: "AppBar",
            path: "TrainingDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_mqg8uqfl",
                  type: "Container",
                  path: "TrainingDetailPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "e7i8ceji",
                      type: "Image",
                      path: "TrainingDetailPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_i9vqrqnf",
                  type: "Text",
                  path: "TrainingDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Training",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ra9cr8ye",
            type: "Column",
            path: "TrainingDetailPage.body[0]",
            name: "TrainingDetailColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_rrcmi4ye",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[0]",
                name: "TrainHeaderCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_i8hygm4a",
                    type: "Column",
                    path: "TrainingDetailPage.body[0].children[0].children[0]",
                    name: "TrainHeaderCol",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_wc3gy4ym",
                        type: "Row",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[0]",
                        name: "TrainHeaderRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_cyoztgvr",
                            type: "Container",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "TrainCircle_event",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_1izmb10b",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_165twqav",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "TrainHeaderInfo",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_538ek1i1",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[0]",
                                name: "TrainDetailDay",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_d1l7v307",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1]",
                                name: "TrainDateLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_el1aru6p",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_j03loox4",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                    name: "TrainDetailDate",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_jwcwimmm",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2]",
                                name: "TrainTimeLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_w80js108",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_9he6yl8o",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[1]",
                                    name: "TrainDetailTime",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_tuw5s6xy",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3]",
                                name: "TrainLocLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_fugbdmss",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_lo4ymsif",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[1]",
                                    name: "TrainDetailLoc",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_1sqwwyjk",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4]",
                                name: "TrainDetailKleedkamerRow",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_tany680n",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_muf61ds0",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[1]",
                                    name: "TrainDetailKleedkamer",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_qqujg3jl",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[1]",
                        name: "TrainStatusPill_aangemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_zob84yzu",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0]",
                            name: "TrainStatusPillRow_aangemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_ga1sn6qu",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_jklm57f8",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[1]",
                                name: "TrainStatusPillText_aangemeld",
                                text: "Aangemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_ih6e1ydn",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[2]",
                        name: "TrainStatusPill_afgemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_gfrqudo4",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0]",
                            name: "TrainStatusPillRow_afgemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_u2f9h0hz",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_0b05jajo",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[1]",
                                name: "TrainStatusPillText_afgemeld",
                                text: "Afgemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_0xdz900t",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[1]",
                name: "TrainAfgelastBanner",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_npdecvav",
                    type: "Row",
                    path: "TrainingDetailPage.body[0].children[1].children[0]",
                    name: "TrainAfgelastRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_utri9qqx",
                        type: "Icon",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_r0qt4u5u",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[1]",
                        name: "TrainAfgelastCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_9luyzryc",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[0]",
                            name: "TrainAfgelastTitel",
                            text: "Afgelast",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_lmbx0kgt",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[1]",
                            name: "TrainAfgelastReden",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_66rkn9bt",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[2]",
                name: "TrainReasonCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_1gm1bamx",
                    type: "Row",
                    path: "TrainingDetailPage.body[0].children[2].children[0]",
                    name: "TrainReasonRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_9rbilvr5",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[2].children[0].children[0]",
                        name: "TrainCircle_comment",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_kz39gxhp",
                            type: "Icon",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_q9c79zx5",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[2].children[0].children[1]",
                        name: "TrainReasonCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_fqcw5wci",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[1].children[0]",
                            name: "TrainReasonLabel",
                            text: "Reden (bij afmelden)",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_r97zw3yi",
                            type: "TextField",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[1].children[1]",
                            name: "TrainReasonField",
                            text: "Geef een reden op (optioneel)",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_1v1c4ppn",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[3]",
                name: "TrainAfmeldHeader",
                text: "Afmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_omssjdzb",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[4]",
                name: "TrainAfmeldButton",
                text: "Afmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_1831wh19",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[5]",
                name: "TrainAanmeldHeader",
                text: "Aanmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_2r8cv63w",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[6]",
                name: "TrainAanmeldButton",
                text: "Aanmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_eqva6dr6",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[7]",
                name: "TrainAfgelastButton",
                text: "Training afgelasten",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_a5xbbdhk",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[8]",
                name: "TrainVrijgeefButton",
                text: "Toch laten doorgaan",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_imfz60na",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[9]",
                name: "TrainAttendanceCard Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_12tpj4b7",
                    type: "Container",
                    path: "TrainingDetailPage.body[0].children[9].children[0]",
                    name: "TrainAttendanceCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_7ap89k81",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0]",
                        name: "TrainAttendanceCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_e11vxdgr",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0]",
                            name: "TrainAanwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_iai849x7",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0]",
                                name: "TrainAanwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_xj887cqg",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[0]",
                                    name: "TrainAanwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_3pqwizh9",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_9e41w04z",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1]",
                                    name: "TrainAanwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_4xjqhfyl",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        name: "TrainAanwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_4lnybkek",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        name: "TrainAanwezigSubtitle",
                                        text: "Deze spelers worden verwacht.",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_a12yp9d0",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[2]",
                                    name: "TrainAanwezigCountPill",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_24nyxcep",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[2].children[0]",
                                        name: "TrainAanwezigCountText",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_reoke0ga",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1]",
                                name: "TrainAanwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_em1yngbo",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0]",
                                    name: "TrainAanwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_viu8snmf",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0]",
                                        name: "TrainAanwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_iau9rz9d",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[0]",
                                            name: "TrainAanwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_bwpol2ei",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_zhgkvsos",
                                            type: "Text",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[1]",
                                            name: "TrainAanwezigNaam",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_cgb31fz8",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[2]",
                                            name: "TrainAanwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_r13b6sk8",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAanwezigToggleLabel",
                                                text: "Afmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_dbp6xhz9",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1]",
                            name: "TrainAfwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_qqj1ik8m",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0]",
                                name: "TrainAfwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_ok5ppzsr",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[0]",
                                    name: "TrainAfwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_0b59ixzg",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_8k7t1sxm",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1]",
                                    name: "TrainAfwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_hcardept",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1].children[0]",
                                        name: "TrainAfwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_mh6ve35h",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1].children[1]",
                                        name: "TrainAfwezigSubtitle",
                                        text: "Deze spelers hebben zich afgemeld.",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_i39btx5g",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1]",
                                name: "TrainAfwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_srqpdhev",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0]",
                                    name: "TrainAfwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_8rui0y4t",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0]",
                                        name: "TrainAfwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_mhfe3kp3",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[0]",
                                            name: "TrainAfwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_us39xo1f",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_5zmieek1",
                                            type: "Column",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1]",
                                            name: "TrainAfwezigNaamCol",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_nshhl4y8",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[0]",
                                                name: "TrainAfwezigNaam",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_pful56is",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[1]",
                                                name: "TrainAfwezigReden",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_3fqkdsqb",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[2]",
                                            name: "TrainAfwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_z1bkigcl",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAfwezigToggleLabel",
                                                text: "Aanmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

