// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final trainingDetailPageHandle = ffai.ProjectPageHandle<TrainingDetailPageParams, TrainingDetailPageState>(
  name: "TrainingDetailPage",
  key: "Scaffold_ugu84our",
  route: "training-detail",
  params: const TrainingDetailPageParams(),
  state: const TrainingDetailPageState(),
  widgets: TrainingDetailPageWidgets.tree,
);

final class TrainingDetailPageParams {
  const TrainingDetailPageParams();
  ffai.ProjectParamHandle get afgelastReden =>
      const ffai.ProjectParamHandle(
        name: "afgelastReden",
        key: "w2ohogkb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get afmeldingen =>
      const ffai.ProjectParamHandle(
        name: "afmeldingen",
        key: "dvk0551g",
        typeName: "List<DataStruct<Afmelding>>",
      );
  ffai.ProjectParamHandle get date =>
      const ffai.ProjectParamHandle(
        name: "date",
        key: "fedg1u52",
        typeName: "String",
      );
  ffai.ProjectParamHandle get dayLabel =>
      const ffai.ProjectParamHandle(
        name: "dayLabel",
        key: "8wv8jfc7",
        typeName: "String",
      );
  ffai.ProjectParamHandle get isAfgelast =>
      const ffai.ProjectParamHandle(
        name: "isAfgelast",
        key: "nn9x8nkp",
        typeName: "String",
      );
  ffai.ProjectParamHandle get kleedkamer =>
      const ffai.ProjectParamHandle(
        name: "kleedkamer",
        key: "8i599a9x",
        typeName: "String",
      );
  ffai.ProjectParamHandle get location =>
      const ffai.ProjectParamHandle(
        name: "location",
        key: "j4fqpnqb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get magAfgelasten =>
      const ffai.ProjectParamHandle(
        name: "magAfgelasten",
        key: "us61te7s",
        typeName: "String",
      );
  ffai.ProjectParamHandle get mijnStatus =>
      const ffai.ProjectParamHandle(
        name: "mijnStatus",
        key: "f0c6wea0",
        typeName: "String",
      );
  ffai.ProjectParamHandle get scheduleId =>
      const ffai.ProjectParamHandle(
        name: "scheduleId",
        key: "tulrxfdo",
        typeName: "String",
      );
  ffai.ProjectParamHandle get startTime =>
      const ffai.ProjectParamHandle(
        name: "startTime",
        key: "ue0z4203",
        typeName: "String",
      );
}

final class TrainingDetailPageState {
  const TrainingDetailPageState();
  ffai.ProjectStateFieldHandle get localAfgelast =>
      const ffai.ProjectStateFieldHandle(
        name: "localAfgelast",
        key: "eyiwip3m",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get localAfgelastReden =>
      const ffai.ProjectStateFieldHandle(
        name: "localAfgelastReden",
        key: "sn0wqtca",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get localStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "localStatus",
        key: "mkxqui0d",
        typeName: "String",
      );
}

abstract final class TrainingDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ugu84our",
      type: "Scaffold",
      path: "TrainingDetailPage",
      name: "TrainingDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_esilfi4x",
            type: "AppBar",
            path: "TrainingDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_mqg8uqfl",
                  type: "Container",
                  path: "TrainingDetailPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "e7i8ceji",
                      type: "Image",
                      path: "TrainingDetailPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_i9vqrqnf",
                  type: "Text",
                  path: "TrainingDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Training",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ra9cr8ye",
            type: "Column",
            path: "TrainingDetailPage.body[0]",
            name: "TrainingDetailColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_wba599l5",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[0]",
                name: "TrainHeaderCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_hrveicsl",
                    type: "Column",
                    path: "TrainingDetailPage.body[0].children[0].children[0]",
                    name: "TrainHeaderCol",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_inlswmxr",
                        type: "Row",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[0]",
                        name: "TrainHeaderRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_w1iz3ssc",
                            type: "Container",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "TrainCircle_event",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_c53rn1w4",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_8ptbdtx5",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "TrainHeaderInfo",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_rxijlyra",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[0]",
                                name: "TrainDetailDay",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_oy16qoir",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1]",
                                name: "TrainDateLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_z9mcid3a",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_vtuaanl9",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                    name: "TrainDetailDate",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_b9lm7qib",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2]",
                                name: "TrainTimeLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_pcqqatdt",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_7hcs7pfm",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[1]",
                                    name: "TrainDetailTime",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_1fpvtqlo",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3]",
                                name: "TrainLocLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_nacs3k1a",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_v7a97f3y",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[1]",
                                    name: "TrainDetailLoc",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_h63kkag3",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4]",
                                name: "TrainDetailKleedkamerRow",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_ur1ryhq9",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_8nh4lbor",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[1]",
                                    name: "TrainDetailKleedkamer",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_1xum9ul1",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[1]",
                        name: "TrainStatusPill_aangemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_8mz4kdnr",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0]",
                            name: "TrainStatusPillRow_aangemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_jjkgxmhp",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_uf13mx1z",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[1]",
                                name: "TrainStatusPillText_aangemeld",
                                text: "Aangemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_s29x269j",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[2]",
                        name: "TrainStatusPill_afgemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_6kx3vlkd",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0]",
                            name: "TrainStatusPillRow_afgemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_oamhc6qe",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ztsupolq",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[1]",
                                name: "TrainStatusPillText_afgemeld",
                                text: "Afgemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_s0ewe44g",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[1]",
                name: "TrainAfgelastBanner",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_x1eqet06",
                    type: "Row",
                    path: "TrainingDetailPage.body[0].children[1].children[0]",
                    name: "TrainAfgelastRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Icon_7rcxuo3r",
                        type: "Icon",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[0]",
                        name: "Icon",
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_50vyre5m",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[1]",
                        name: "TrainAfgelastCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_77gk7da3",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[0]",
                            name: "TrainAfgelastTitel",
                            text: "Afgelast",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_pxbrls0m",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[1]",
                            name: "TrainAfgelastReden",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_jxxl62om",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[2]",
                name: "TrainReasonCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_fkw2sx71",
                    type: "Row",
                    path: "TrainingDetailPage.body[0].children[2].children[0]",
                    name: "TrainReasonRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ai0jyzux",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[2].children[0].children[0]",
                        name: "TrainCircle_comment",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_vr82rp71",
                            type: "Icon",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_ta01mhtj",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[2].children[0].children[1]",
                        name: "TrainReasonCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_blpxl9st",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[1].children[0]",
                            name: "TrainReasonLabel",
                            text: "Reden (bij afmelden)",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_xgbm0iyb",
                            type: "TextField",
                            path: "TrainingDetailPage.body[0].children[2].children[0].children[1].children[1]",
                            name: "TrainReasonField",
                            text: "Geef een reden op (optioneel)",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_ebqrolaj",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[3]",
                name: "TrainAfmeldHeader",
                text: "Afmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_x0hin7cb",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[4]",
                name: "TrainAfmeldButton",
                text: "Afmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_ca7wjz39",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[5]",
                name: "TrainAanmeldHeader",
                text: "Aanmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_f7nl1l27",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[6]",
                name: "TrainAanmeldButton",
                text: "Aanmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_1w3dl1k9",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[7]",
                name: "TrainAfgelastButton",
                text: "Training afgelasten",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_n39356lh",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[8]",
                name: "TrainVrijgeefButton",
                text: "Toch laten doorgaan",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_cf4el6g9",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[9]",
                name: "TrainAttendanceCard Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_b5op88n9",
                    type: "Container",
                    path: "TrainingDetailPage.body[0].children[9].children[0]",
                    name: "TrainAttendanceCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_1bcmwanv",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0]",
                        name: "TrainAttendanceCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_bf16r8bw",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0]",
                            name: "TrainAanwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_o0g5hyqe",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0]",
                                name: "TrainAanwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_chtewkpg",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[0]",
                                    name: "TrainAanwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_1p9yf8am",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_ho6xad93",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1]",
                                    name: "TrainAanwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_rg550f26",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        name: "TrainAanwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_7zpk5ec1",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        name: "TrainAanwezigSubtitle",
                                        text: "Deze spelers worden verwacht.",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_6bi9312o",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[2]",
                                    name: "TrainAanwezigCountPill",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_ekbqs9ze",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[0].children[2].children[0]",
                                        name: "TrainAanwezigCountText",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_285h0626",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1]",
                                name: "TrainAanwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_frbxwuhx",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0]",
                                    name: "TrainAanwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_o05rix98",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0]",
                                        name: "TrainAanwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_hb9p2kiz",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[0]",
                                            name: "TrainAanwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_2f6ueh2m",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_6gx188pz",
                                            type: "Text",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[1]",
                                            name: "TrainAanwezigNaam",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_ul1ni907",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[2]",
                                            name: "TrainAanwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_izgd5un0",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAanwezigToggleLabel",
                                                text: "Afmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_jeg948am",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1]",
                            name: "TrainAfwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_y9dcqn27",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0]",
                                name: "TrainAfwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_y0e8dbgb",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[0]",
                                    name: "TrainAfwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_3oe2ul7v",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_wc0u62a5",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1]",
                                    name: "TrainAfwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_02fa103o",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1].children[0]",
                                        name: "TrainAfwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_l57rsbtn",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[0].children[1].children[1]",
                                        name: "TrainAfwezigSubtitle",
                                        text: "Deze spelers hebben zich afgemeld.",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_9mcgenoy",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1]",
                                name: "TrainAfwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_hgi8gs7e",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0]",
                                    name: "TrainAfwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_suo4mhxo",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0]",
                                        name: "TrainAfwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_gd7pmpmn",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[0]",
                                            name: "TrainAfwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_yg9we1of",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_akuw5yd4",
                                            type: "Column",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1]",
                                            name: "TrainAfwezigNaamCol",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_u5tt801d",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[0]",
                                                name: "TrainAfwezigNaam",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_d4wafv44",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[1]",
                                                name: "TrainAfwezigReden",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_y2f8zjav",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[2]",
                                            name: "TrainAfwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_1hwtjmjy",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[9].children[0].children[0].children[1].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAfwezigToggleLabel",
                                                text: "Aanmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

