// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final trainingenPageHandle = ffai.ProjectPageHandle<TrainingenPageParams, TrainingenPageState>(
  name: "TrainingenPage",
  key: "Scaffold_ntde1gjv",
  route: "trainingen",
  params: const TrainingenPageParams(),
  state: const TrainingenPageState(),
  widgets: TrainingenPageWidgets.tree,
);

final class TrainingenPageParams {
  const TrainingenPageParams();
}

final class TrainingenPageState {
  const TrainingenPageState();
  ffai.ProjectStateFieldHandle get bannerImageUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "bannerImageUrl",
        key: "egoj2xza",
        typeName: "String",
      );
  ffai.ProjectStateFieldHandle get bannerLinkUrl =>
      const ffai.ProjectStateFieldHandle(
        name: "bannerLinkUrl",
        key: "1qkabjbk",
        typeName: "String",
      );
}

abstract final class TrainingenPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ntde1gjv",
      type: "Scaffold",
      path: "TrainingenPage",
      name: "TrainingenPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_i84wliw5",
            type: "AppBar",
            path: "TrainingenPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_zb0irk68",
                  type: "Container",
                  path: "TrainingenPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "sr1prhaz",
                      type: "Image",
                      path: "TrainingenPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_2qw1yzxu",
                  type: "Text",
                  path: "TrainingenPage.appBar[0].title[0]",
                  name: "TrainingenAppBarTitle",
                  text: "Trainingen",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_by4eflmo",
            type: "Column",
            path: "TrainingenPage.body[0]",
            name: "TrainingenBodyColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_4wfqbz4j",
                type: "Container",
                path: "TrainingenPage.body[0].children[0]",
                name: "TrainingenBannerContainer",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Image_d0li25a9",
                    type: "Image",
                    path: "TrainingenPage.body[0].children[0].children[0]",
                    name: "TrainingenBannerImage",
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "d11sfea0",
                type: "Stack",
                path: "TrainingenPage.body[0].children[1]",
                name: "TrainingenPageBodyStack",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_rf5ieua9",
                    type: "Column",
                    path: "TrainingenPage.body[0].children[1].children[0]",
                    name: "Column",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_rl7lcrzq",
                        type: "Container",
                        path: "TrainingenPage.body[0].children[1].children[0].children[0]",
                        name: "TrainingenListContainer",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_dhigng6t",
                            type: "Column",
                            path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "TrainingenListCol",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "ListView_nee815oc",
                                type: "ListView",
                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0]",
                                name: "TrainingenList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5c87w3uo",
                                    type: "Container",
                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0]",
                                    name: "TrainingenCard",
                                    triggers: const <String>[
                                      "ON_TAP",
                                    ],
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_f0zpab4d",
                                        type: "Row",
                                        path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "TrainingenCardRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_zyohkqaw",
                                            type: "Container",
                                            path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                            name: "TrainingenCardIconWrap",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_1c1suin1",
                                                type: "Icon",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_xcj4yoag",
                                            type: "Column",
                                            path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1]",
                                            name: "TrainingenCardInfo",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_j5zt3yea",
                                                type: "Text",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[0]",
                                                name: "TrainingenCardDay",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_o9d2z5tw",
                                                type: "Row",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1]",
                                                name: "TrainingenCardWhen",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_18ahnewh",
                                                    type: "Text",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                                    name: "TrainingenCardDate",
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_i62qgru6",
                                                    type: "Text",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                                    name: "TrainingenCardTime",
                                                  ),
                                                ],
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_vnbr96r2",
                                                type: "Row",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[2]",
                                                name: "TrainingenCardLocRow",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_fyg2ylwr",
                                                    type: "Icon",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[2].children[0]",
                                                    name: "Icon",
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_2184gcw6",
                                                    type: "Text",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[1].children[2].children[1]",
                                                    name: "TrainingenCardLoc",
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_zm2znghb",
                                            type: "Container",
                                            path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[2]",
                                            name: "TrainingenCardAfgelast",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_n822k4fr",
                                                type: "Text",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[2].children[0]",
                                                name: "TrainingenCardAfgelastLabel",
                                                text: "Afgelast",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_v2hpqm3z",
                                            type: "Column",
                                            path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3]",
                                            name: "TrainingenCardCounts",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_1umz9mpv",
                                                type: "Row",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0]",
                                                name: "TrainingenCardAanmeldRow",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_euh3oyqb",
                                                    type: "Icon",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[0]",
                                                    name: "Icon",
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_qk8v1pem",
                                                    type: "Text",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[0].children[1]",
                                                    name: "TrainingenCardAanmeld",
                                                  ),
                                                ],
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Row_7e06o9n3",
                                                type: "Row",
                                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[1]",
                                                name: "TrainingenCardAfmeldRow",
                                                children: <ffai.ProjectWidgetHandle>[
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Icon_4ocflkfm",
                                                    type: "Icon",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[1].children[0]",
                                                    name: "Icon",
                                                  ),
                                                  ffai.ProjectWidgetHandle(
                                                    key: "Text_9r3i2bou",
                                                    type: "Text",
                                                    path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[0].children[0].children[0].children[3].children[1].children[1]",
                                                    name: "TrainingenCardAfmeld",
                                                  ),
                                                ],
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_ae4y043d",
                                type: "Text",
                                path: "TrainingenPage.body[0].children[1].children[0].children[0].children[0].children[1]",
                                name: "TrainingenEmpty",
                                text: "Er staan nog geen trainingen gepland.",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_hl4wxe9j",
                    type: "Container",
                    path: "TrainingenPage.body[0].children[1].children[1]",
                    name: "ChatBadgeOverlay",
                  ),
                ],
              ),
            ],
          ),
        ],
        "drawer": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Drawer_rkzm56vk",
            type: "Drawer",
            path: "TrainingenPage.drawer[0]",
            name: "AppDrawer",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Column_un7xgfbt",
                type: "Column",
                path: "TrainingenPage.drawer[0].children[0]",
                name: "DrawerMenuColumn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_8hock8bo",
                    type: "Container",
                    path: "TrainingenPage.drawer[0].children[0].children[0]",
                    name: "DrawerHeader",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_3qb26k5u",
                        type: "Column",
                        path: "TrainingenPage.drawer[0].children[0].children[0].children[0]",
                        name: "DrawerHeaderColumn",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_0gshzx3b",
                            type: "Container",
                            path: "TrainingenPage.drawer[0].children[0].children[0].children[0].children[0]",
                            name: "DrawerHeaderAvatar",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "5t9mbfs5",
                                type: "CircleImage",
                                path: "TrainingenPage.drawer[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "DrawerHeaderPhoto",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Icon_pedt21b3",
                                type: "Icon",
                                path: "TrainingenPage.drawer[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_n1p9wph4",
                            type: "Text",
                            path: "TrainingenPage.drawer[0].children[0].children[0].children[0].children[1]",
                            name: "DrawerHeaderName",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_sbya41hq",
                            type: "Text",
                            path: "TrainingenPage.drawer[0].children[0].children[0].children[0].children[2]",
                            name: "DrawerHeaderEmail",
                          ),
                        ],
                      ),
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_prvfo3ki",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[1]",
                    name: "DrawerTileHome",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_hfb27rby",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[2]",
                    name: "DrawerTileNews",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_ti8c0tcj",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[3]",
                    name: "DrawerTileDocs",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_355w405a",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[4]",
                    name: "DrawerTileProfiel",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_fqeijz3p",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[5]",
                    name: "DrawerTileMijnCode",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "ListTile_hjxrzsmi",
                    type: "ListTile",
                    path: "TrainingenPage.drawer[0].children[0].children[6]",
                    name: "DrawerTileBug",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_rqskrf66",
                    type: "Container",
                    path: "TrainingenPage.drawer[0].children[0].children[7]",
                    name: "DrawerFooterSpacer",
                  ),
                  ffai.ProjectWidgetHandle(
                    key: "Container_0e21dqcp",
                    type: "Container",
                    path: "TrainingenPage.drawer[0].children[0].children[8]",
                    name: "DrawerFooterLogoWrap",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_18vvxwut",
                        type: "Row",
                        path: "TrainingenPage.drawer[0].children[0].children[8].children[0]",
                        name: "DrawerFooterLogoRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "zzung5no",
                            type: "Image",
                            path: "TrainingenPage.drawer[0].children[0].children[8].children[0].children[0]",
                            name: "DrawerFooterLogo",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

