// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final trainingDetailPageHandle = ffai.ProjectPageHandle<TrainingDetailPageParams, TrainingDetailPageState>(
  name: "TrainingDetailPage",
  key: "Scaffold_ugu84our",
  route: "training-detail",
  params: const TrainingDetailPageParams(),
  state: const TrainingDetailPageState(),
  widgets: TrainingDetailPageWidgets.tree,
);

final class TrainingDetailPageParams {
  const TrainingDetailPageParams();
  ffai.ProjectParamHandle get afmeldingen =>
      const ffai.ProjectParamHandle(
        name: "afmeldingen",
        key: "dvk0551g",
        typeName: "List<DataStruct<Afmelding>>",
      );
  ffai.ProjectParamHandle get date =>
      const ffai.ProjectParamHandle(
        name: "date",
        key: "fedg1u52",
        typeName: "String",
      );
  ffai.ProjectParamHandle get dayLabel =>
      const ffai.ProjectParamHandle(
        name: "dayLabel",
        key: "8wv8jfc7",
        typeName: "String",
      );
  ffai.ProjectParamHandle get kleedkamer =>
      const ffai.ProjectParamHandle(
        name: "kleedkamer",
        key: "8i599a9x",
        typeName: "String",
      );
  ffai.ProjectParamHandle get location =>
      const ffai.ProjectParamHandle(
        name: "location",
        key: "j4fqpnqb",
        typeName: "String",
      );
  ffai.ProjectParamHandle get mijnStatus =>
      const ffai.ProjectParamHandle(
        name: "mijnStatus",
        key: "f0c6wea0",
        typeName: "String",
      );
  ffai.ProjectParamHandle get scheduleId =>
      const ffai.ProjectParamHandle(
        name: "scheduleId",
        key: "tulrxfdo",
        typeName: "String",
      );
  ffai.ProjectParamHandle get startTime =>
      const ffai.ProjectParamHandle(
        name: "startTime",
        key: "ue0z4203",
        typeName: "String",
      );
}

final class TrainingDetailPageState {
  const TrainingDetailPageState();
  ffai.ProjectStateFieldHandle get localStatus =>
      const ffai.ProjectStateFieldHandle(
        name: "localStatus",
        key: "mkxqui0d",
        typeName: "String",
      );
}

abstract final class TrainingDetailPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_ugu84our",
      type: "Scaffold",
      path: "TrainingDetailPage",
      name: "TrainingDetailPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_esilfi4x",
            type: "AppBar",
            path: "TrainingDetailPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_mqg8uqfl",
                  type: "Container",
                  path: "TrainingDetailPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "e7i8ceji",
                      type: "Image",
                      path: "TrainingDetailPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_i9vqrqnf",
                  type: "Text",
                  path: "TrainingDetailPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Training",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_ra9cr8ye",
            type: "Column",
            path: "TrainingDetailPage.body[0]",
            name: "TrainingDetailColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_dkst7mhz",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[0]",
                name: "TrainHeaderCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Column_d33w7k9x",
                    type: "Column",
                    path: "TrainingDetailPage.body[0].children[0].children[0]",
                    name: "TrainHeaderCol",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_k5vmox7l",
                        type: "Row",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[0]",
                        name: "TrainHeaderRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_w5lt9h9l",
                            type: "Container",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "TrainCircle_event",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_tweng491",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "Icon",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_qgs6dctk",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "TrainHeaderInfo",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_74z15qbv",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[0]",
                                name: "TrainDetailDay",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_axligsab",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1]",
                                name: "TrainDateLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_27g1lyx2",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_hc9r3hvb",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[1].children[1]",
                                    name: "TrainDetailDate",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_xpp0p9l6",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2]",
                                name: "TrainTimeLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_d8r4egdp",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_lvgulzjh",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[2].children[1]",
                                    name: "TrainDetailTime",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_xlipcyt2",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3]",
                                name: "TrainLocLine",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_3du7zk5t",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_7g0kmcy0",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[3].children[1]",
                                    name: "TrainDetailLoc",
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_ugl3zhuh",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4]",
                                name: "TrainDetailKleedkamerRow",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Icon_63v42kgr",
                                    type: "Icon",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[0]",
                                    name: "Icon",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_j5socymb",
                                    type: "Text",
                                    path: "TrainingDetailPage.body[0].children[0].children[0].children[0].children[1].children[4].children[1]",
                                    name: "TrainDetailKleedkamer",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_5y0cp68i",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[1]",
                        name: "TrainStatusPill_aangemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_5gboziop",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0]",
                            name: "TrainStatusPillRow_aangemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_rk598vds",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_bxfdsepl",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[1].children[0].children[1]",
                                name: "TrainStatusPillText_aangemeld",
                                text: "Aangemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Container_hltgki8t",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[0].children[0].children[2]",
                        name: "TrainStatusPill_afgemeld",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_ib52qabz",
                            type: "Row",
                            path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0]",
                            name: "TrainStatusPillRow_afgemeld",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Icon_wewyzg8e",
                                type: "Icon",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[0]",
                                name: "Icon",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_g43yhhuw",
                                type: "Text",
                                path: "TrainingDetailPage.body[0].children[0].children[0].children[2].children[0].children[1]",
                                name: "TrainStatusPillText_afgemeld",
                                text: "Afgemeld",
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_8cpyweyp",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[1]",
                name: "TrainReasonCard",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Row_jqxbow74",
                    type: "Row",
                    path: "TrainingDetailPage.body[0].children[1].children[0]",
                    name: "TrainReasonRow",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Container_ujmxyvcj",
                        type: "Container",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[0]",
                        name: "TrainCircle_comment",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Icon_ze5wckb3",
                            type: "Icon",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[0].children[0]",
                            name: "Icon",
                          ),
                        ],
                      ),
                      ffai.ProjectWidgetHandle(
                        key: "Column_mwrqsi2p",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[1].children[0].children[1]",
                        name: "TrainReasonCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Text_3e2z6gsf",
                            type: "Text",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[0]",
                            name: "TrainReasonLabel",
                            text: "Reden (bij afmelden)",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "TextField_l26smfjg",
                            type: "TextField",
                            path: "TrainingDetailPage.body[0].children[1].children[0].children[1].children[1]",
                            name: "TrainReasonField",
                            text: "Geef een reden op (optioneel)",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_5nww8ovu",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[2]",
                name: "TrainAfmeldHeader",
                text: "Afmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_e8jfdw47",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[3]",
                name: "TrainAfmeldButton",
                text: "Afmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_0ruo161y",
                type: "Text",
                path: "TrainingDetailPage.body[0].children[4]",
                name: "TrainAanmeldHeader",
                text: "Aanmelden voor deze training",
              ),
              ffai.ProjectWidgetHandle(
                key: "Button_r0l8fg7u",
                type: "Button",
                path: "TrainingDetailPage.body[0].children[5]",
                name: "TrainAanmeldButton",
                text: "Aanmelden",
                triggers: const <String>[
                  "ON_TAP",
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Container_bsqjpq2b",
                type: "Container",
                path: "TrainingDetailPage.body[0].children[6]",
                name: "TrainAttendanceCard Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_nwwq2dc8",
                    type: "Container",
                    path: "TrainingDetailPage.body[0].children[6].children[0]",
                    name: "TrainAttendanceCard",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Column_mvmiyi53",
                        type: "Column",
                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0]",
                        name: "TrainAttendanceCol",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_d6gkk9gx",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0]",
                            name: "TrainAanwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_xaggfqsh",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0]",
                                name: "TrainAanwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_5qaj60sd",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[0]",
                                    name: "TrainAanwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_2nhjad3p",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_1x73a051",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[1]",
                                    name: "TrainAanwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_tjdbjj22",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[1].children[0]",
                                        name: "TrainAanwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_h5nfws5y",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[1].children[1]",
                                        name: "TrainAanwezigSubtitle",
                                        text: "Deze spelers worden verwacht.",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_j3e4g365",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[2]",
                                    name: "TrainAanwezigCountPill",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_xbm64lrr",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[0].children[2].children[0]",
                                        name: "TrainAanwezigCountText",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_fguio7dd",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1]",
                                name: "TrainAanwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_dq87w65f",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0]",
                                    name: "TrainAanwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_hhcmjkzr",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0]",
                                        name: "TrainAanwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_kk6goae3",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0].children[0]",
                                            name: "TrainAanwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_cd255yv4",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Text_al39jolj",
                                            type: "Text",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0].children[1]",
                                            name: "TrainAanwezigNaam",
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_pee26q5n",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0].children[2]",
                                            name: "TrainAanwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_22u48ekx",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[0].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAanwezigToggleLabel",
                                                text: "Afmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_9gkvnq4o",
                            type: "Column",
                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1]",
                            name: "TrainAfwezig",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Row_c20z7y9v",
                                type: "Row",
                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0]",
                                name: "TrainAfwezigHead",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_h2pk7gbw",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0].children[0]",
                                    name: "TrainAfwezigHeadIcon",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_2mugdzk1",
                                        type: "Icon",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Column_005e6a36",
                                    type: "Column",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0].children[1]",
                                    name: "TrainAfwezigHeadCol",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_7rfdsyxz",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0].children[1].children[0]",
                                        name: "TrainAfwezigTitle",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Text_fyblwest",
                                        type: "Text",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[0].children[1].children[1]",
                                        name: "TrainAfwezigSubtitle",
                                        text: "Deze spelers hebben zich afgemeld.",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "ListView_pb7fmmo2",
                                type: "ListView",
                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1]",
                                name: "TrainAfwezigList",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Container_yk56e7pj",
                                    type: "Container",
                                    path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0]",
                                    name: "TrainAfwezigItem",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Row_bxyorwol",
                                        type: "Row",
                                        path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0]",
                                        name: "TrainAfwezigRow",
                                        children: <ffai.ProjectWidgetHandle>[
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_sp7uy2vh",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[0]",
                                            name: "TrainAfwezigBadge",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Icon_3rwnohiv",
                                                type: "Icon",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[0].children[0]",
                                                name: "Icon",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Column_sprmrcy2",
                                            type: "Column",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[1]",
                                            name: "TrainAfwezigNaamCol",
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_br3rp6ms",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[0]",
                                                name: "TrainAfwezigNaam",
                                              ),
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_qrqm1zm1",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[1].children[1]",
                                                name: "TrainAfwezigReden",
                                              ),
                                            ],
                                          ),
                                          ffai.ProjectWidgetHandle(
                                            key: "Container_3omsmhhq",
                                            type: "Container",
                                            path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[2]",
                                            name: "TrainAfwezigToggle",
                                            triggers: const <String>[
                                              "ON_TAP",
                                            ],
                                            children: <ffai.ProjectWidgetHandle>[
                                              ffai.ProjectWidgetHandle(
                                                key: "Text_c211mg18",
                                                type: "Text",
                                                path: "TrainingDetailPage.body[0].children[6].children[0].children[0].children[1].children[1].children[0].children[0].children[2].children[0]",
                                                name: "TrainAfwezigToggleLabel",
                                                text: "Aanmelden",
                                              ),
                                            ],
                                          ),
                                        ],
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

