// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final verslagPageHandle = ffai.ProjectPageHandle<VerslagPageParams, VerslagPageState>(
  name: "VerslagPage",
  key: "Scaffold_hm4g57ow",
  route: "verslag",
  params: const VerslagPageParams(),
  state: const VerslagPageState(),
  widgets: VerslagPageWidgets.tree,
);

final class VerslagPageParams {
  const VerslagPageParams();
  ffai.ProjectParamHandle get dateLabel =>
      const ffai.ProjectParamHandle(
        name: "dateLabel",
        key: "cnej8km8",
        typeName: "String",
      );
  ffai.ProjectParamHandle get matchId =>
      const ffai.ProjectParamHandle(
        name: "matchId",
        key: "ubzmuvqw",
        typeName: "String",
      );
  ffai.ProjectParamHandle get opponent =>
      const ffai.ProjectParamHandle(
        name: "opponent",
        key: "ocpv0ayt",
        typeName: "String",
      );
  ffai.ProjectParamHandle get score =>
      const ffai.ProjectParamHandle(
        name: "score",
        key: "vegdxnv2",
        typeName: "String",
      );
  ffai.ProjectParamHandle get teamName =>
      const ffai.ProjectParamHandle(
        name: "teamName",
        key: "ai9yn6w3",
        typeName: "String",
      );
}

final class VerslagPageState {
  const VerslagPageState();
}

abstract final class VerslagPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_hm4g57ow",
      type: "Scaffold",
      path: "VerslagPage",
      name: "VerslagPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_50an7rto",
            type: "AppBar",
            path: "VerslagPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_fyqsb7rn",
                  type: "Container",
                  path: "VerslagPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "oc8wid0z",
                      type: "Image",
                      path: "VerslagPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_h5df0seu",
                  type: "Text",
                  path: "VerslagPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Verslag",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_k0upbeq8",
            type: "Column",
            path: "VerslagPage.body[0]",
            name: "VerslagRootColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_yhnwyn8j",
                type: "Container",
                path: "VerslagPage.body[0].children[0]",
                name: "VerslagKopKaart Margin",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_cfh9iggz",
                    type: "Container",
                    path: "VerslagPage.body[0].children[0].children[0]",
                    name: "VerslagKopKaart",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_budo4s4w",
                        type: "Row",
                        path: "VerslagPage.body[0].children[0].children[0].children[0]",
                        name: "VerslagKopRij",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Column_kulg1qhd",
                            type: "Column",
                            path: "VerslagPage.body[0].children[0].children[0].children[0].children[0]",
                            name: "VerslagKopCol",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_srjq90mx",
                                type: "Text",
                                path: "VerslagPage.body[0].children[0].children[0].children[0].children[0].children[0]",
                                name: "VerslagKopTegenstander",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_pi8ff3r4",
                                type: "Text",
                                path: "VerslagPage.body[0].children[0].children[0].children[0].children[0].children[1]",
                                name: "VerslagKopTeam",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Text_d900y7uy",
                                type: "Text",
                                path: "VerslagPage.body[0].children[0].children[0].children[0].children[0].children[2]",
                                name: "VerslagKopDatum",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_2sleq6a9",
                            type: "Text",
                            path: "VerslagPage.body[0].children[0].children[0].children[0].children[1]",
                            name: "VerslagKopScore",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_xvi51jiu",
                type: "Text",
                path: "VerslagPage.body[0].children[1]",
                name: "VerslagLeeg",
                text: "Van deze wedstrijd is geen verslag bijgehouden.",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_qmi737ul",
                type: "ListView",
                path: "VerslagPage.body[0].children[2]",
                name: "VerslagTijdlijn",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_051xvf3l",
                    type: "Container",
                    path: "VerslagPage.body[0].children[2].children[0]",
                    name: "VerslagTijdlijnItem",
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_vmu6tu6o",
                        type: "Row",
                        path: "VerslagPage.body[0].children[2].children[0].children[0]",
                        name: "VerslagTijdlijnRow",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Row_bug5d4tk",
                            type: "Row",
                            path: "VerslagPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "VerslagTijdlijnBadge",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Container_859ss47n",
                                type: "Container",
                                path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "VerslagTijdlijnBadgeHot",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_31cs2kox",
                                    type: "Row",
                                    path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0]",
                                    name: "VerslagTijdlijnHotIcons",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_ti0nnlkc",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kemysa5c",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_40y90sih",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[2]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_gvodze4g",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[3]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_kefba8tc",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[0].children[0].children[4]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Container_hjhg22yz",
                                type: "Container",
                                path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1]",
                                name: "VerslagTijdlijnBadgeCalm",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Row_b5vrvxoz",
                                    type: "Row",
                                    path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0]",
                                    name: "VerslagTijdlijnCalmIcons",
                                    children: <ffai.ProjectWidgetHandle>[
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_3cdc6ry1",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0].children[0]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_zk2n9dkm",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0].children[1]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_trfashfj",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0].children[2]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_mtqih044",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0].children[3]",
                                        name: "Icon",
                                      ),
                                      ffai.ProjectWidgetHandle(
                                        key: "Icon_0kjwof4m",
                                        type: "Icon",
                                        path: "VerslagPage.body[0].children[2].children[0].children[0].children[0].children[1].children[0].children[4]",
                                        name: "Icon",
                                      ),
                                    ],
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_yb99ki96",
                            type: "Container",
                            path: "VerslagPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "VerslagTijdlijnCard",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Column_ihwhnr66",
                                type: "Column",
                                path: "VerslagPage.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "VerslagTijdlijnCardCol",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_cmaygw0b",
                                    type: "Text",
                                    path: "VerslagPage.body[0].children[2].children[0].children[0].children[1].children[0].children[0]",
                                    name: "VerslagTijdlijnMinute",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_rxqq3btq",
                                    type: "Text",
                                    path: "VerslagPage.body[0].children[2].children[0].children[0].children[1].children[0].children[1]",
                                    name: "VerslagTijdlijnLabel",
                                  ),
                                ],
                              ),
                            ],
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

