// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final wedstrijdverslagenPageHandle = ffai.ProjectPageHandle<WedstrijdverslagenPageParams, WedstrijdverslagenPageState>(
  name: "WedstrijdverslagenPage",
  key: "Scaffold_3adrn1x7",
  route: "wedstrijdverslagen",
  params: const WedstrijdverslagenPageParams(),
  state: const WedstrijdverslagenPageState(),
  widgets: WedstrijdverslagenPageWidgets.tree,
);

final class WedstrijdverslagenPageParams {
  const WedstrijdverslagenPageParams();
}

final class WedstrijdverslagenPageState {
  const WedstrijdverslagenPageState();
}

abstract final class WedstrijdverslagenPageWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Scaffold_3adrn1x7",
      type: "Scaffold",
      path: "WedstrijdverslagenPage",
      name: "WedstrijdverslagenPage",
      triggers: const <String>[
        "ON_INIT_STATE",
      ],
      slots: <String, List<ffai.ProjectWidgetHandle>>{
        "appBar": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "AppBar_i0s2ul7q",
            type: "AppBar",
            path: "WedstrijdverslagenPage.appBar[0]",
            name: "AppBar",
            slots: <String, List<ffai.ProjectWidgetHandle>>{
              "actions": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Container_ps8drk2i",
                  type: "Container",
                  path: "WedstrijdverslagenPage.appBar[0].actions[0]",
                  name: "ClubLogoAppBarWrap",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "g611bx5f",
                      type: "Image",
                      path: "WedstrijdverslagenPage.appBar[0].actions[0].children[0]",
                      name: "ClubLogoAppBar",
                    ),
                  ],
                ),
              ],
              "title": <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_j71l219m",
                  type: "Text",
                  path: "WedstrijdverslagenPage.appBar[0].title[0]",
                  name: "AppBar Title",
                  text: "Wedstrijdverslagen",
                ),
              ],
            },
          ),
        ],
        "body": <ffai.ProjectWidgetHandle>[
          ffai.ProjectWidgetHandle(
            key: "Column_uhvslci1",
            type: "Column",
            path: "WedstrijdverslagenPage.body[0]",
            name: "VerslagenRootColumn",
            children: <ffai.ProjectWidgetHandle>[
              ffai.ProjectWidgetHandle(
                key: "Container_zm6cn9re",
                type: "Container",
                path: "WedstrijdverslagenPage.body[0].children[0]",
                name: "VerslagenZoekWrap",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "TextField_sawy0hp1",
                    type: "TextField",
                    path: "WedstrijdverslagenPage.body[0].children[0].children[0]",
                    name: "VerslagenZoekVeld",
                    text: "Zoek op tegenstander of elftal",
                    triggers: const <String>[
                      "ON_TEXTFIELD_CHANGE",
                    ],
                  ),
                ],
              ),
              ffai.ProjectWidgetHandle(
                key: "Text_l0ani76l",
                type: "Text",
                path: "WedstrijdverslagenPage.body[0].children[1]",
                name: "VerslagenMelding",
              ),
              ffai.ProjectWidgetHandle(
                key: "ListView_u2m0d0c0",
                type: "ListView",
                path: "WedstrijdverslagenPage.body[0].children[2]",
                name: "VerslagenList",
                children: <ffai.ProjectWidgetHandle>[
                  ffai.ProjectWidgetHandle(
                    key: "Container_mpwbaleo",
                    type: "Container",
                    path: "WedstrijdverslagenPage.body[0].children[2].children[0]",
                    name: "VerslagKaart",
                    triggers: const <String>[
                      "ON_TAP",
                    ],
                    children: <ffai.ProjectWidgetHandle>[
                      ffai.ProjectWidgetHandle(
                        key: "Row_dy8n9qp8",
                        type: "Row",
                        path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0]",
                        name: "VerslagRij",
                        children: <ffai.ProjectWidgetHandle>[
                          ffai.ProjectWidgetHandle(
                            key: "Container_j9esss53",
                            type: "Container",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[0]",
                            name: "VerslagUitslagW",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_p2349kfj",
                                type: "Text",
                                path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[0].children[0]",
                                name: "VerslagUitslagWTekst",
                                text: "W",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_m8nlj0vb",
                            type: "Container",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[1]",
                            name: "VerslagUitslagG",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_46ow1o4r",
                                type: "Text",
                                path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[1].children[0]",
                                name: "VerslagUitslagGTekst",
                                text: "G",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Container_z01s3o21",
                            type: "Container",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[2]",
                            name: "VerslagUitslagV",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_4tahlt75",
                                type: "Text",
                                path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[2].children[0]",
                                name: "VerslagUitslagVTekst",
                                text: "V",
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Column_6k9rq1qz",
                            type: "Column",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3]",
                            name: "VerslagNaamCol",
                            children: <ffai.ProjectWidgetHandle>[
                              ffai.ProjectWidgetHandle(
                                key: "Text_xjvcx9c6",
                                type: "Text",
                                path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3].children[0]",
                                name: "VerslagTegenstander",
                              ),
                              ffai.ProjectWidgetHandle(
                                key: "Row_wltieiyw",
                                type: "Row",
                                path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3].children[1]",
                                name: "VerslagOnderRij",
                                children: <ffai.ProjectWidgetHandle>[
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_56bxmjzr",
                                    type: "Text",
                                    path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3].children[1].children[0]",
                                    name: "VerslagDatum",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_u9uri9ps",
                                    type: "Text",
                                    path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3].children[1].children[1]",
                                    name: "VerslagScheiding",
                                    text: "·",
                                  ),
                                  ffai.ProjectWidgetHandle(
                                    key: "Text_hk8ecumv",
                                    type: "Text",
                                    path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[3].children[1].children[2]",
                                    name: "VerslagTeam",
                                  ),
                                ],
                              ),
                            ],
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Text_jplgh2y7",
                            type: "Text",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[4]",
                            name: "VerslagScore",
                          ),
                          ffai.ProjectWidgetHandle(
                            key: "Icon_qi1ipjp2",
                            type: "Icon",
                            path: "WedstrijdverslagenPage.body[0].children[2].children[0].children[0].children[5]",
                            name: "Icon",
                          ),
                        ],
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      },
    ),
  );
}

