// GENERATED CODE - DO NOT EDIT.
// Generated by FlutterFlow AI from the FFProject proto.
library;

import 'package:flutterflow_ai/flutterflow_ai.dart' as ffai;

final class MatchActionsSheetComponentHandle extends ffai.ProjectComponentHandle<MatchActionsSheetParams, MatchActionsSheetState> {
  MatchActionsSheetComponentHandle()
    : super(
        name: "MatchActionsSheet",
        key: "Container_elxocmyr",
        params: const MatchActionsSheetParams(),
        state: const MatchActionsSheetState(),
        widgets: MatchActionsSheetWidgets.tree,
        paramTypes: <String, ffai.DslType>{
        },
      );

  ffai.ComponentInstance call({
    String? name,
    Object? visible,
  }) {
    return buildInstance(
      name: name,
      visible: visible,
      paramArgs: <String, Object?>{
      },
    );
  }
}

final class MatchActionsSheetParams {
  const MatchActionsSheetParams();
}

final class MatchActionsSheetState {
  const MatchActionsSheetState();
}

abstract final class MatchActionsSheetWidgets {
  static final tree = ffai.ProjectWidgetTree(
    root: ffai.ProjectWidgetHandle(
      key: "Container_elxocmyr",
      type: "Container",
      path: "MatchActionsSheet",
      name: "MatchActionsSheet",
      children: <ffai.ProjectWidgetHandle>[
        ffai.ProjectWidgetHandle(
          key: "Column_casrz1gt",
          type: "Column",
          path: "MatchActionsSheet.children[0]",
          name: "MatchActionsRoot",
          children: <ffai.ProjectWidgetHandle>[
            ffai.ProjectWidgetHandle(
              key: "Text_9ll1x4ui",
              type: "Text",
              path: "MatchActionsSheet.children[0].children[0]",
              name: "MaTitle",
              text: "Wedstrijd-actie",
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_8x9wd44f",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[1]",
              name: "MaMenuView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Button_41rgf22i",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[1].children[0]",
                  name: "MaMenuBtn_goal",
                  text: "Doelpunt toevoegen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_ww364yym",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[1].children[1]",
                  name: "MaMenuBtn_flag",
                  text: "Vlagger kiezen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_3jypw4ry",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[1].children[2]",
                  name: "MaMenuBtn_fruit",
                  text: "Fruitheld kiezen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_zg2s5i7v",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[1].children[3]",
                  name: "MaMenuBtn_invite",
                  text: "Gastspeler uitnodigen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_4brz8ifz",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[1].children[4]",
                  name: "MaMenuBtn_note",
                  text: "Notitie toevoegen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_up3v15av",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[2]",
              name: "MaGoalView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_up8rw0so",
                  type: "Text",
                  path: "MatchActionsSheet.children[0].children[2].children[0]",
                  name: "MaGoalLabel",
                  text: "Kies de speler en plaats:",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_crcfx7af",
                  type: "Container",
                  path: "MatchActionsSheet.children[0].children[2].children[1]",
                  name: "MaScorerScroll",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "ListView_oxh1nn44",
                      type: "ListView",
                      path: "MatchActionsSheet.children[0].children[2].children[1].children[0]",
                      name: "MaScorerList",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_m4rthw9o",
                          type: "Container",
                          path: "MatchActionsSheet.children[0].children[2].children[1].children[0].children[0]",
                          name: "MaScorerRow",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_qjo6wi46",
                              type: "Text",
                              path: "MatchActionsSheet.children[0].children[2].children[1].children[0].children[0].children[0]",
                              name: "MaScorerName",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "TextField_zuw4eqq9",
                  type: "TextField",
                  path: "MatchActionsSheet.children[0].children[2].children[2]",
                  name: "MaMinuteField",
                  text: "Minuut (optioneel)",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_6d2pzisl",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[2].children[3]",
                  name: "MaPlaceBtn",
                  text: "Doelpunt plaatsen",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_k46rop05",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[2].children[4]",
                  name: "MaBackBtn_voo2my3o",
                  text: "Terug",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_heatmtwa",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[3]",
              name: "MaNoteView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_143vv3nu",
                  type: "Text",
                  path: "MatchActionsSheet.children[0].children[3].children[0]",
                  name: "MaNoteLabel",
                  text: "Zichtbaar voor iedereen bij deze wedstrijd. Laat leeg om te wissen.",
                ),
                ffai.ProjectWidgetHandle(
                  key: "TextField_y7j2he3i",
                  type: "TextField",
                  path: "MatchActionsSheet.children[0].children[3].children[1]",
                  name: "MaNoteField",
                  text: "Notitie bij deze wedstrijd",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_egtz23ic",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[3].children[2]",
                  name: "MaSaveNoteBtn",
                  text: "Notitie opslaan",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_7cg1ocsn",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[3].children[3]",
                  name: "MaBackBtn_nzcdtpyh",
                  text: "Terug",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_w3xgbwkj",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[4]",
              name: "MaFlagView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_iyzhpuyp",
                  type: "Text",
                  path: "MatchActionsSheet.children[0].children[4].children[0]",
                  name: "MaFlagLabel",
                  text: "Kies de vlagger (uit het team):",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_q1sysu9r",
                  type: "Container",
                  path: "MatchActionsSheet.children[0].children[4].children[1]",
                  name: "MaFlagScroll",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "ListView_fskty3c0",
                      type: "ListView",
                      path: "MatchActionsSheet.children[0].children[4].children[1].children[0]",
                      name: "MaFlagList",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_flpcttdw",
                          type: "Container",
                          path: "MatchActionsSheet.children[0].children[4].children[1].children[0].children[0]",
                          name: "MaFlagRow",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_64249r14",
                              type: "Text",
                              path: "MatchActionsSheet.children[0].children[4].children[1].children[0].children[0].children[0]",
                              name: "MaFlagName",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Column_zhbb21gz",
                  type: "Column",
                  path: "MatchActionsSheet.children[0].children[4].children[2]",
                  name: "MaFlagConfirm",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_4it5dy1a",
                      type: "Text",
                      path: "MatchActionsSheet.children[0].children[4].children[2].children[0]",
                      name: "MaFlagSelected",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Button_e1wh3d2y",
                      type: "Button",
                      path: "MatchActionsSheet.children[0].children[4].children[2].children[1]",
                      name: "MaAddFlagBtn",
                      text: "Vlagger toevoegen",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_fek5pd3u",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[4].children[3]",
                  name: "MaClearFlagBtn",
                  text: "Geen vlagger",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_r0ua38l0",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[4].children[4]",
                  name: "MaBackBtn_kq5mpau9",
                  text: "Terug",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_2b6dhhf1",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[5]",
              name: "MaFruitView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_4kab1gvw",
                  type: "Text",
                  path: "MatchActionsSheet.children[0].children[5].children[0]",
                  name: "MaFruitLabel",
                  text: "Kies de fruitheld (uit het team):",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_4yw22uqd",
                  type: "Container",
                  path: "MatchActionsSheet.children[0].children[5].children[1]",
                  name: "MaFruitScroll",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "ListView_hobzxp6f",
                      type: "ListView",
                      path: "MatchActionsSheet.children[0].children[5].children[1].children[0]",
                      name: "MaFruitList",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_2rxnvgif",
                          type: "Container",
                          path: "MatchActionsSheet.children[0].children[5].children[1].children[0].children[0]",
                          name: "MaFruitRow",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_sio67yqh",
                              type: "Text",
                              path: "MatchActionsSheet.children[0].children[5].children[1].children[0].children[0].children[0]",
                              name: "MaFruitName",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Column_arh4517a",
                  type: "Column",
                  path: "MatchActionsSheet.children[0].children[5].children[2]",
                  name: "MaFruitConfirm",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_l3xcoecq",
                      type: "Text",
                      path: "MatchActionsSheet.children[0].children[5].children[2].children[0]",
                      name: "MaFruitSelected",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Button_7jbnw3ag",
                      type: "Button",
                      path: "MatchActionsSheet.children[0].children[5].children[2].children[1]",
                      name: "MaAddFruitBtn",
                      text: "Fruitheld toevoegen",
                      triggers: const <String>[
                        "ON_TAP",
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_ol9pe47j",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[5].children[3]",
                  name: "MaClearFruitBtn",
                  text: "Geen fruitheld",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_bo8byp7e",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[5].children[4]",
                  name: "MaBackBtn_bbpv8sba",
                  text: "Terug",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
            ffai.ProjectWidgetHandle(
              key: "Column_5i5nkzgh",
              type: "Column",
              path: "MatchActionsSheet.children[0].children[6]",
              name: "MaInviteView",
              children: <ffai.ProjectWidgetHandle>[
                ffai.ProjectWidgetHandle(
                  key: "Text_9zvuuxvz",
                  type: "Text",
                  path: "MatchActionsSheet.children[0].children[6].children[0]",
                  name: "MaInviteLabel",
                  text: "Kies eerst het team:",
                ),
                ffai.ProjectWidgetHandle(
                  key: "Container_2eocgwp7",
                  type: "Container",
                  path: "MatchActionsSheet.children[0].children[6].children[1]",
                  name: "MaTeamsScroll",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "ListView_g01zwi7w",
                      type: "ListView",
                      path: "MatchActionsSheet.children[0].children[6].children[1].children[0]",
                      name: "MaTeamsList",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Container_k3bv46s1",
                          type: "Container",
                          path: "MatchActionsSheet.children[0].children[6].children[1].children[0].children[0]",
                          name: "MaTeamRow",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Text_ng8njvra",
                              type: "Text",
                              path: "MatchActionsSheet.children[0].children[6].children[1].children[0].children[0].children[0]",
                              name: "MaTeamName",
                            ),
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Column_iezyx114",
                  type: "Column",
                  path: "MatchActionsSheet.children[0].children[6].children[2]",
                  name: "MaGuestSection",
                  children: <ffai.ProjectWidgetHandle>[
                    ffai.ProjectWidgetHandle(
                      key: "Text_zgtgn6e4",
                      type: "Text",
                      path: "MatchActionsSheet.children[0].children[6].children[2].children[0]",
                      name: "MaGuestLabel",
                      text: "Kies de gastspeler:",
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Container_yxt78we9",
                      type: "Container",
                      path: "MatchActionsSheet.children[0].children[6].children[2].children[1]",
                      name: "MaGuestScroll",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "ListView_o80qmfgn",
                          type: "ListView",
                          path: "MatchActionsSheet.children[0].children[6].children[2].children[1].children[0]",
                          name: "MaGuestList",
                          children: <ffai.ProjectWidgetHandle>[
                            ffai.ProjectWidgetHandle(
                              key: "Container_egioby38",
                              type: "Container",
                              path: "MatchActionsSheet.children[0].children[6].children[2].children[1].children[0].children[0]",
                              name: "MaGuestRow",
                              triggers: const <String>[
                                "ON_TAP",
                              ],
                              children: <ffai.ProjectWidgetHandle>[
                                ffai.ProjectWidgetHandle(
                                  key: "Text_jgxhfwu1",
                                  type: "Text",
                                  path: "MatchActionsSheet.children[0].children[6].children[2].children[1].children[0].children[0].children[0]",
                                  name: "MaGuestName",
                                ),
                              ],
                            ),
                          ],
                        ),
                      ],
                    ),
                    ffai.ProjectWidgetHandle(
                      key: "Column_6113wwxt",
                      type: "Column",
                      path: "MatchActionsSheet.children[0].children[6].children[2].children[2]",
                      name: "MaGuestConfirm",
                      children: <ffai.ProjectWidgetHandle>[
                        ffai.ProjectWidgetHandle(
                          key: "Text_4e2t3mp3",
                          type: "Text",
                          path: "MatchActionsSheet.children[0].children[6].children[2].children[2].children[0]",
                          name: "MaGuestSelected",
                        ),
                        ffai.ProjectWidgetHandle(
                          key: "Button_ti5gkyu9",
                          type: "Button",
                          path: "MatchActionsSheet.children[0].children[6].children[2].children[2].children[1]",
                          name: "MaAddGuestBtn",
                          text: "Gastspeler toevoegen",
                          triggers: const <String>[
                            "ON_TAP",
                          ],
                        ),
                      ],
                    ),
                  ],
                ),
                ffai.ProjectWidgetHandle(
                  key: "Button_ttvz8t7j",
                  type: "Button",
                  path: "MatchActionsSheet.children[0].children[6].children[3]",
                  name: "MaBackBtn_31ymnjsx",
                  text: "Terug",
                  triggers: const <String>[
                    "ON_TAP",
                  ],
                ),
              ],
            ),
          ],
        ),
      ],
    ),
  );
}

